export const TRADE_OPTIONS = [
  'Electrician',
  'HVAC Technician',
  'Plumber',
  'Roofer',
  'Carpenter',
  'Machine Technician',
  'Welder',
  'Refrigeration Technician',
  'Pipefitter',
  'Sheet Metal Worker',
  'Mason / Concrete Worker',
  'Drywall / Painter',
  'Glazier',
  'Insulation Installer',
  'Boilermaker',
  'Fire Protection / Sprinkler Tech',
  'Solar Installer',
  'Low-Voltage / Telecom Tech',
  'Locksmith',
  'Appliance Repair Tech',
  'Equipment Operator',
  'General Laborer / Helper',
];

export const TRADE_OTHER_SENTINEL = '__other__';
