from .common import q

SAFETY = [
    q(
        "easy",
        "Before touching conductors in a panel, what is the safest sequence?",
        "Identify the circuit, de-energize, lock out/tag out, and verify absence of voltage with a meter that has been tested on a known live source.",
        "De-energize, lock out/tag out, and verify with a meter",
        [
            "Grab the conductor quickly to see if it shocks",
            "Rely only on a breaker handle position without testing",
            "Remove the equipment grounding conductor first so the circuit cannot return",
        ],
    ),
    q(
        "easy",
        "Why is eye protection required when cutting, drilling, or pulling wire in occupied walls?",
        "Metal shavings, masonry dust, and snapping conductors can injure eyes. Safety glasses are basic PPE.",
        "Debris and snapping conductors can injure the eyes",
        [
            "Eye protection is only for welding",
            "Electrical work cannot produce flying particles",
            "A paper dust mask is complete eye protection",
        ],
    ),
    q(
        "easy",
        "A GFCI device is intended primarily to protect against:",
        "A GFCI opens when it detects imbalance between the ungrounded and grounded conductors, reducing shock hazard. It is not an overcurrent device for conductor ampacity.",
        "Shock from ground-fault current through a person or leakage path",
        [
            "Overloaded conductors the same way a breaker does",
            "High utility voltage sags",
            "Low transformer impedance",
        ],
    ),
    q(
        "easy",
        "Why should jewelry and conductive watches be removed around energized equipment?",
        "Metal jewelry can bridge live parts and cause burns. De-energize when possible; do not wear conductive jewelry around live work.",
        "Metal jewelry can short live parts and cause burns",
        [
            "Jewelry improves grip on insulated tools",
            "Conductive jewelry is required PPE",
            "Watches protect against arc flash",
        ],
    ),
    q(
        "easy",
        "What is the purpose of an insulated hand tool rated for electrical work?",
        "The insulation is a barrier if contact with an energized part occurs. It is not a substitute for de-energizing, and damaged insulation must not be used.",
        "To provide a dielectric barrier if a live part is contacted",
        [
            "To magnetize fasteners",
            "To increase torque beyond the tool’s mechanical rating",
            "To replace lockout/tagout",
        ],
    ),
    q(
        "easy",
        "A ladder used near overhead electrical lines should be:",
        "Use nonconductive ladders and maintain safe approach distances. Metal ladders near overhead lines are a shock hazard.",
        "Nonconductive and kept a safe distance from overhead lines",
        [
            "Aluminum, because metal is safer near power lines",
            "Placed so the rails rest on the conductors for stability",
            "Wet, so it cannot conduct",
        ],
    ),
    q(
        "easy",
        "Why must a circuit be identified before it is opened for repair?",
        "The wrong breaker can leave the circuit live. Trace, identify, de-energize, and verify. Guessing among similar breakers is unsafe.",
        "So the correct circuit is de-energized and verified dead",
        [
            "Identification is only for billing the utility",
            "Any breaker in the panel de-energizes every circuit",
            "Neutral bars cannot remain energized if one breaker is off",
        ],
    ),
    q(
        "medium",
        "What is lockout/tagout intended to prevent?",
        "LOTO prevents unexpected re-energization while someone is working. A note on a phone is not a lockout.",
        "Unexpected energization or startup while work is in progress",
        [
            "Utility brownouts",
            "GFCI nuisance trips only",
            "Voltage drop in long feeders",
        ],
    ),
    q(
        "medium",
        "An arc-flash hazard exists when:",
        "A fault can release intense heat and light. De-energize when possible and use appropriate PPE and procedures when live work is justified. Cotton street clothes are not arc-rated PPE.",
        "A fault can release a high-energy electrical explosion of heat and light",
        [
            "Only when working on fiber-optic cable",
            "Only on extra-low-voltage doorbells",
            "Never on 208/240-volt equipment",
        ],
    ),
    q(
        "medium",
        "Why should a meter be checked on a known live source before and after proving a circuit dead?",
        "A failed meter can read zero on a live circuit. Live-dead-live verification confirms the instrument works.",
        "To confirm the meter is working so a zero reading is trustworthy",
        [
            "Because meters cannot be trusted on known live sources",
            "To drain the meter’s internal battery faster",
            "To magnetize the probes",
        ],
    ),
    q(
        "medium",
        "A confined space with electrical equipment may also have atmospheric hazards. What should be considered before extended work?",
        "Vaults and pits can have oxygen deficiency or toxic gases in addition to shock hazards. Assess the atmosphere and electrical isolation together.",
        "Atmospheric hazards as well as electrical hazards",
        [
            "Only noise, never atmosphere",
            "That vaults are always safe if a flashlight works",
            "That a paper mask is complete confined-space protection",
        ],
    ),
    q(
        "medium",
        "Damaged insulation on a flexible cord should be:",
        "Damaged cords are a shock and fire hazard. Take them out of service. Tape is not a permanent repair for portable cord on a construction site.",
        "Taken out of service and replaced or properly repaired",
        [
            "Wrapped with a single layer of masking tape as a permanent repair",
            "Used only in wet locations so the water cools the copper",
            "Overfused so the cord can carry more current",
        ],
    ),
    q(
        "medium",
        "When drilling into a wall, why is looking for existing cables, pipes, and a safe boring location important?",
        "Drilling into concealed conductors can cause shock and arc. Use detectors, open a visual inspection where needed, and follow boring/notching rules.",
        "Concealed conductors can be punctured, creating shock and arc hazards",
        [
            "Cables are never run in walls",
            "Drill bits cannot cut copper",
            "A metal fish tape in a live conduit is the preferred locator",
        ],
    ),
    q(
        "medium",
        "Why is standing on a wet floor while working in a panel a concern even if the panel cover is on?",
        "Moisture lowers contact resistance to ground and increases shock severity. Dry, stable footing and de-energized work reduce risk.",
        "Water lowers resistance to ground and increases shock risk",
        [
            "Water is an insulator at panel voltages",
            "Wet floors reduce arc-flash energy",
            "GFCI on a lighting circuit makes wet-floor panel work risk-free",
        ],
    ),
    q(
        "medium",
        "Temporary jobsite lighting and cords should be arranged so that:",
        "Cords should be protected from damage, not create trip hazards, and be suitable for the location. Daisy-chaining damaged strips is a common fire/trip hazard.",
        "They are protected from damage and do not create trip or shock hazards",
        [
            "They run through doorways un-protected so they are visible",
            "They are covered with carpet in a wet walkway",
            "They are fused above the cord’s ampacity so they do not trip",
        ],
    ),
    q(
        "medium",
        "A live-front panelboard with the cover off should be treated as:",
        "Exposed energized parts require work practices and PPE appropriate to the hazard, and work should be de-energized when possible. Casual clothing is not adequate.",
        "An exposed-energized-parts hazard until it is de-energized and verified",
        [
            "Safe because the breakers have handles",
            "Safe if the worker is wearing a cotton hoodie",
            "Safe for jewelry because the bus is recessed",
        ],
    ),
    q(
        "medium",
        "Why must unused openings in boxes and enclosures be closed?",
        "Openings expose live parts, allow debris entry, and can violate listing. Use listed closures, not cardboard.",
        "To prevent exposure of live parts and keep the enclosure’s protection intact",
        [
            "To increase ventilation around breakers as a design goal",
            "Because openings improve GFCI function",
            "So rodents can inspect splices",
        ],
    ),
    q(
        "medium",
        "A helper is about to reset a breaker that tripped while someone is still working downstream. What should happen?",
        "Never re-energize a circuit until it is confirmed clear and people are clear. Investigate the trip. Communication is part of LOTO.",
        "Do not re-energize until the circuit is clear and the cause is understood",
        [
            "Reset immediately so work can continue under load",
            "Tape the breaker on so it cannot trip again",
            "Install a larger breaker without investigation",
        ],
    ),
    q(
        "medium",
        "Voltage-rated gloves must be:",
        "Inspected, used within rating and date requirements, and paired with leather protectors as required. Damaged gloves must be removed from service.",
        "Inspected and used within their rating; damaged gloves taken out of service",
        [
            "Used after cutting off the leather protectors for better feel as a standard practice",
            "Held together with tape after a puncture",
            "Used as the only control while standing in water on an unidentified circuit",
        ],
    ),
    q(
        "hard",
        "A 480-volt motor disconnect is tagged out, but a separate control-power transformer still energizes a 120-volt circuit in the same enclosure. What is the lesson?",
        "Equipment can have multiple energy sources. Isolating the motor feeder does not isolate control power, heaters, or foreign voltage. Identify all sources and verify each.",
        "All energy sources in the enclosure must be identified, isolated, and verified",
        [
            "Motor disconnects always isolate every voltage in the cabinet",
            "120-volt control circuits cannot shock",
            "Tags without energy isolation are sufficient if they say DANGER",
        ],
    ),
    q(
        "hard",
        "An electrician must work near an overhead line that cannot be de-energized. What is the appropriate approach?",
        "Maintain required approach distances, use spotters, nonconductive equipment, and utility coordination. Do not guess distances from the ground with a metal tape.",
        "Maintain required clearances, use nonconductive equipment, and coordinate with the utility",
        [
            "Touch the line with a metal fish tape to see if it is live",
            "Assume insulated service drop covering is touch-safe for a ladder",
            "Raise a metal scaffold until it is just below the conductors",
        ],
    ),
    q(
        "hard",
        "A fault occurs and a worker is frozen to a live part. What is the correct first priority for a rescuer?",
        "Do not grab the person with bare hands. De-energize or use an insulating rescue method. Then call emergency services. This is about not becoming a second victim.",
        "De-energize or separate the person with insulating means; do not touch them with bare hands",
        [
            "Pull the person free with bare hands as fast as possible",
            "Pour water on both people to cool the burn while they remain in contact",
            "Reset the breaker so the circuit can help let go",
        ],
    ),
    q(
        "hard",
        "Infrared scanning of a loaded panel is planned. Why is removing the dead-front without a work plan a problem?",
        "Removing covers exposes live parts. Scanning should follow electrical safety procedures, appropriate PPE, and closed-cover IR windows when used. Do not casually open a loaded 480-volt board in street clothes.",
        "Removing covers exposes live parts and requires an electrical-safety work plan",
        [
            "IR scans are harmless because cameras are plastic",
            "Loaded panels cannot arc if the camera is battery powered",
            "Street clothes are arc-rated if they are dark-colored",
        ],
    ),
    q(
        "hard",
        "A generator is backfeeding a building during an outage through a dryer receptacle. Why is this unsafe?",
        "Backfeeding can energize service conductors and kill a lineworker, and it can overpower cords and transfer equipment. Use a listed transfer switch or interlock that prevents utility and generator interconnection.",
        "It can energize utility lines and overloads unlisted cords/connections",
        [
            "Portable generators cannot produce lethal voltage",
            "Backfeeding through a receptacle is the listed transfer method",
            "Utility transformers block all backfeed by design in every case",
        ],
    ),
]

THEORY = [
    q(
        "easy",
        "Ohm’s law relates voltage, current, and resistance as:",
        "E = I × R (or V = I R). Power is a different quantity (P = I × E).",
        "Voltage equals current times resistance",
        [
            "Voltage equals current divided by resistance always",
            "Current equals voltage times resistance",
            "Resistance equals voltage times current",
        ],
    ),
    q(
        "easy",
        "Current in a circuit is:",
        "Current is the flow of electric charge, measured in amperes.",
        "The flow of electric charge",
        [
            "Opposition to flow, measured in ohms",
            "Electrical pressure, measured in volts",
            "Energy stored in a capacitor only",
        ],
    ),
    q(
        "easy",
        "Resistance is measured in:",
        "Resistance is measured in ohms. Conductance is measured in siemens; inductance in henries; capacitance in farads.",
        "Ohms",
        [
            "Amperes",
            "Volts",
            "Watts",
        ],
    ),
    q(
        "easy",
        "In a series circuit, current is:",
        "Series current is the same through each component. Voltage divides across resistances.",
        "The same through each component",
        [
            "Different through each resistor and lowest at the source",
            "Always zero after the first lamp",
            "Inversely proportional to voltage only, never resistance",
        ],
    ),
    q(
        "easy",
        "In a parallel circuit, voltage across each branch is:",
        "Parallel branches share the same voltage; currents add.",
        "The same across each branch",
        [
            "Split so each branch gets a fraction of the source voltage always",
            "Zero on all but one branch",
            "Equal to the sum of the branch voltages",
        ],
    ),
    q(
        "easy",
        "Power in a DC circuit can be calculated as:",
        "P = I × E, also P = I²R and P = E²/R for resistive circuits.",
        "Volts times amperes",
        [
            "Volts divided by amperes only",
            "Ohms times volts only",
            "Amperes divided by ohms only",
        ],
    ),
    q(
        "easy",
        "A transformer’s primary function is to:",
        "A transformer transfers AC power between circuits, typically changing voltage by the turns ratio. It does not create DC without additional components.",
        "Change AC voltage (and current) between circuits by magnetic coupling",
        [
            "Convert AC to chemical energy",
            "Store energy like a battery",
            "Increase frequency from 60 Hz to 400 Hz automatically",
        ],
    ),
    q(
        "medium",
        "A 120-volt heater draws 10 amperes. What is the power?",
        "P = 120 × 10 = 1,200 watts.",
        "1,200 watts",
        [
            "12 watts",
            "1.2 watts",
            "120 kilowatts",
        ],
    ),
    q(
        "medium",
        "Two 10-ohm resistors in parallel have an equivalent resistance of:",
        "Equal parallel resistors: R/n = 10/2 = 5 ohms.",
        "5 ohms",
        [
            "20 ohms",
            "10 ohms",
            "100 ohms",
        ],
    ),
    q(
        "medium",
        "A conductor’s resistance increases when:",
        "Resistance rises with length, with higher temperature (for copper), and with smaller cross-section. It is not reduced by using a longer wire.",
        "It is longer, smaller in cross-section, or hotter (for copper)",
        [
            "It is shorter and thicker",
            "It is cooled and shortened",
            "Its circular mil area is increased while length stays the same",
        ],
    ),
    q(
        "medium",
        "Inductive loads such as motors cause current to:",
        "Inductance makes current lag voltage. Power factor is less than 1. This is why motor circuits can have higher current than a same-wattage resistive heater.",
        "Lag the voltage",
        [
            "Lead the voltage like a capacitor always does in every motor",
            "Remain exactly in phase regardless of inductance",
            "Stop at the first winding",
        ],
    ),
    q(
        "medium",
        "A capacitor stores energy in:",
        "A capacitor stores energy in an electric field between plates. An inductor stores energy in a magnetic field.",
        "An electric field",
        [
            "A magnetic field only, like an inductor",
            "A chemical reaction like a primary battery as its main mechanism",
            "A rotating magnetic field in the rotor bars",
        ],
    ),
    q(
        "medium",
        "Kirchhoff’s current law states that:",
        "The algebraic sum of currents at a node is zero: current in equals current out.",
        "The currents entering a node equal the currents leaving it",
        [
            "Voltage is the same on every series component",
            "Power is always conserved as heat only",
            "Resistance is independent of temperature for all metals",
        ],
    ),
    q(
        "medium",
        "A 3-ohm and a 6-ohm resistor are in series on 18 volts. Current is:",
        "Rt = 9 ohms; I = 18/9 = 2 A.",
        "2 amperes",
        [
            "6 amperes",
            "9 amperes",
            "0.5 ampere",
        ],
    ),
    q(
        "medium",
        "RMS voltage for a sine wave is significant because:",
        "RMS is the effective value that produces the same heating in a resistor as a DC voltage of that value. Meters typically display RMS for AC power circuits.",
        "It is the effective value related to heating in a resistive load",
        [
            "It is always 0.5 times peak for a sine wave",
            "It is the same as average voltage for all waveforms",
            "It only applies to batteries",
        ],
    ),
    q(
        "medium",
        "A motor nameplate lists FLA. This is most nearly:",
        "Full-load amperes is the current at rated load, voltage, and frequency. LRA is locked-rotor (starting) current, which is much higher.",
        "Current at rated load and voltage",
        [
            "Locked-rotor current at start",
            "The branch-circuit breaker rating always",
            "The grounding-electrode conductor size",
        ],
    ),
    q(
        "medium",
        "Power factor is:",
        "Power factor is real power divided by apparent power (W/VA). It is 1.0 for a pure resistor and lower for inductive motors.",
        "Real power divided by apparent power",
        [
            "Voltage divided by current",
            "Resistance times current squared only",
            "The transformer turns ratio",
        ],
    ),
    q(
        "medium",
        "In a balanced 208Y/120-volt system, the voltage from line to neutral is:",
        "Line-to-neutral is 120 volts; line-to-line is 208 volts.",
        "120 volts",
        [
            "208 volts",
            "240 volts",
            "480 volts",
        ],
    ),
    q(
        "medium",
        "A short circuit differs from an overload because a short circuit is:",
        "A short is an unintended low-resistance path and very high current. An overload is excess current within the load path, often modestly above rating.",
        "An unintended low-resistance path that can produce very high current",
        [
            "A slight increase in load current above FLA only",
            "Always a high-resistance leakage through a person",
            "A transformer with too many secondary turns",
        ],
    ),
    q(
        "hard",
        "A 240-volt single-phase load draws 20 A at a power factor of 0.80. Approximate real power is:",
        "P = E × I × PF = 240 × 20 × 0.80 = 3,840 W.",
        "3,840 watts",
        [
            "4,800 watts",
            "240 watts",
            "16 watts",
        ],
    ),
    q(
        "hard",
        "A transformer is 480 V primary to 120 V secondary. If primary current is 5 A (ignoring losses), secondary current is about:",
        "Ampere-turns/power balance: 480×5 ≈ 120×Is → Is ≈ 20 A. Current inverses with voltage.",
        "20 amperes",
        [
            "5 amperes",
            "1.25 amperes",
            "480 amperes",
        ],
    ),
    q(
        "hard",
        "Skin effect at higher frequency causes AC current to:",
        "Current crowds toward the conductor surface, raising effective resistance. It is more relevant at higher frequencies than at 60 Hz for typical small building wire, but the principle is still tested in theory.",
        "Crowd toward the conductor surface, raising effective resistance",
        [
            "Travel only in the steel conduit, never the copper",
            "Stop entirely above 60 Hz",
            "Become DC automatically",
        ],
    ),
    q(
        "hard",
        "A three-phase motor runs with one supply phase lost (single-phasing). What is a likely result?",
        "The motor may try to run with excessive current in the remaining windings, overheating. It should be protected and taken off line; it will not produce full torque.",
        "Overheating and reduced torque in the remaining windings",
        [
            "Higher efficiency than on three phases",
            "No current in any winding",
            "Automatic conversion to a generator at higher voltage",
        ],
    ),
    q(
        "hard",
        "Why can a high-impedance voltmeter show voltage on an open, parallel-run conductor?",
        "Capacitive coupling can impress a phantom voltage. A low-impedance meter or a small load collapses it. Treat unknown readings carefully; verify with an appropriate method.",
        "Capacitive coupling can create a phantom voltage that cannot supply much current",
        [
            "The conductor must be solidly connected to the utility",
            "Phantom voltage only exists on fiber",
            "High-impedance meters cannot display AC",
        ],
    ),
]

CIRCUITS = [
    q(
        "easy",
        "A typical branch circuit consists of:",
        "Ungrounded (hot) conductors, a grounded (neutral) conductor when required, an equipment grounding conductor, and an overcurrent device.",
        "Circuit conductors, an overcurrent device, and an equipment grounding path as required",
        [
            "Only a transformer with no overcurrent device",
            "Only a grounding electrode with no ungrounded conductor",
            "A water pipe used as the only circuit conductor",
        ],
    ),
    q(
        "easy",
        "A switch is generally installed in the:",
        "Switches interrupt the ungrounded conductor. Switching the grounded (neutral) conductor alone can leave equipment energized.",
        "Ungrounded (hot) conductor",
        [
            "Equipment grounding conductor only",
            "Grounding electrode conductor only",
            "Neutral only, leaving the hot continuous as a standard lighting practice",
        ],
    ),
    q(
        "easy",
        "The equipment grounding conductor is intended to:",
        "Bond non-current-carrying metal so fault current can return and open the overcurrent device.",
        "Provide a low-impedance path for fault current",
        [
            "Carry normal load current in place of the neutral",
            "Increase voltage at the load",
            "Replace the overcurrent device",
        ],
    ),
    q(
        "easy",
        "A receptacle’s grounding slot (U-shape or green screw) connects to:",
        "The equipment grounding conductor, which bonds the yoke and downstream metal.",
        "The equipment grounding conductor",
        [
            "The ungrounded hot only",
            "A satellite dish mast as the only required path",
            "The utility meter’s potential coil",
        ],
    ),
    q(
        "easy",
        "Overcurrent devices are selected to protect:",
        "Conductors and equipment from overload and fault current, within their listings and the circuit design.",
        "Conductors and equipment from excessive current",
        [
            "Only the utility transformer primary",
            "The grounding electrode from lightning exclusively",
            "Fiber-optic cables from light overload",
        ],
    ),
    q(
        "easy",
        "A three-way switch loop is used to:",
        "Control a lighting load from two locations. It is not a series heater circuit.",
        "Control a load from two locations",
        [
            "Increase voltage from 120 to 240",
            "Create a separately derived system",
            "Bond a water pipe",
        ],
    ),
    q(
        "easy",
        "A fuse or breaker that opens frequently on a circuit may indicate:",
        "Overload, a fault, or a device mismatch. Replacing it with a larger rating without investigation is unsafe.",
        "Overload, a short/ground fault, or an incorrectly sized device",
        [
            "That the circuit needs a larger unlisted fuse as the first action",
            "That the grounding conductor is too large",
            "That GFCI protection should be removed",
        ],
    ),
    q(
        "medium",
        "A multiwire branch circuit shares a neutral. A key safety practice is:",
        "The ungrounded conductors should be on different phases/legs so the neutral carries difference current, and a means to simultaneously disconnect them is required in many installations. Disconnecting the neutral under load can overvoltage loads.",
        "Keep the ungrounded conductors on different legs and do not open the shared neutral under load",
        [
            "Land both hots on the same bus stab so the neutral carries 2× current as a design",
            "Use the equipment grounding conductor as the shared neutral",
            "Size the shared neutral as a signaling pair",
        ],
    ),
    q(
        "medium",
        "Voltage drop in a long feeder is a concern because:",
        "Excessive drop causes motors to run hot, lights to dim, and electronics to misbehave. Increasing conductor size or reducing length/load are typical remedies.",
        "Loads may overheat or perform poorly at reduced voltage",
        [
            "Voltage drop increases conductor ampacity",
            "Voltage drop is required to operate GFCIs",
            "Motors always need at least 20% drop to start",
        ],
    ),
    q(
        "medium",
        "A GFCI receptacle protecting downstream receptacles does so through:",
        "The load-side terminals feed downstream devices through the GFCI’s current transformer. Line and load reversed will not protect downstream (and may not reset).",
        "Its load-side terminals feeding those devices",
        [
            "The equipment grounding conductor only",
            "A wireless signal to the panel",
            "The water piping",
        ],
    ),
    q(
        "medium",
        "An AFCI is intended to protect against:",
        "Arc-faults that can ignite nearby materials. It is complementary to, not the same as, GFCI personnel protection.",
        "Arcing faults that can start fires",
        [
            "Only utility high voltage",
            "Only motor inrush as a design",
            "Only harmonic currents in LEDs",
        ],
    ),
    q(
        "medium",
        "A contactor or relay coil is on a control circuit, while its contacts may switch:",
        "Coils are often lower voltage; contacts can switch line-voltage loads. Treat both as possible shock hazards.",
        "A separate, possibly higher-voltage load circuit",
        [
            "Only the same extra-low voltage as the coil in every case",
            "Only fiber-optic signals",
            "Only DC when the coil is AC, always",
        ],
    ),
    q(
        "medium",
        "Why are white conductors used as hots in switch loops required to be reidentified?",
        "So the next electrician does not treat an ungrounded conductor as a neutral. Reidentify with marking where required.",
        "To show that the conductor is being used as an ungrounded conductor, not a neutral",
        [
            "To increase ampacity",
            "To allow the white wire to be used as a grounding conductor",
            "Reidentification is only for fiber jackets",
        ],
    ),
    q(
        "medium",
        "A motor starter’s overload relay is intended to protect against:",
        "Sustained overcurrent in the motor from mechanical overload. Short-circuit/ground-fault protection is a different function, usually fuses or a breaker.",
        "Sustained motor overcurrent from overload",
        [
            "Only lightning on the utility line",
            "Only the control transformer primary inrush as its sole job",
            "The grounding electrode resistance",
        ],
    ),
    q(
        "medium",
        "Dimming an LED lighting load with an incompatible dimmer often causes:",
        "Flicker, buzzing, overheating, or failure. Match the dimmer to the load type and listing.",
        "Flicker, noise, or overheating",
        [
            "An automatic increase in conductor ampacity",
            "Conversion of the branch circuit to three-phase",
            "A listed substitute for AFCI protection",
        ],
    ),
    q(
        "medium",
        "A transformer supplying a 120/240-volt panel is a separately derived system when:",
        "When there is no direct electrical connection between primary and secondary (typical isolation transformer) and the secondary is grounded as required. The bonding/grounding arrangement must be made at the derived system.",
        "The secondary is not electrically derived through a direct conductive path from the primary and is grounded/bonded as a new system",
        [
            "A receptacle is added on a branch circuit",
            "A GFCI is installed",
            "A three-way switch is added",
        ],
    ),
    q(
        "medium",
        "Why should aluminum branch-circuit terminations be made with listed connectors and proper torque?",
        "Aluminum oxide and creep can cause high-resistance heating. Use listed connectors (often CO/ALR or Al-rated) and torque. Do not put unmarked aluminum under a copper-only device.",
        "To reduce high-resistance heating from oxidation and conductor creep",
        [
            "Aluminum never needs torque because it is soft",
            "Any copper-only device is acceptable on aluminum",
            "Oil from a refrigeration compressor is the listed antioxidant for all aluminum splices",
        ],
    ),
    q(
        "medium",
        "A photocell or occupancy sensor that switches the hot should not switch the equipment grounding conductor because:",
        "The EGC must remain a continuous fault path. Switching a ground can leave equipment unbonded.",
        "The equipment grounding path must remain continuous",
        [
            "Grounding conductors are supposed to be switched for three-way control",
            "Photocells only work on neutrals",
            "EGCs carry normal load current and must be switched like hots",
        ],
    ),
    q(
        "medium",
        "Inrush current of an incandescent or motor load can:",
        "Briefly exceed running current. Overcurrent devices must be able to handle inrush without nuisance trip while still protecting the conductors.",
        "Exceed running current for a short time",
        [
            "Never exceed FLA",
            "Only occur on fiber circuits",
            "Reduce conductor heating below continuous load",
        ],
    ),
    q(
        "hard",
        "A shared neutral on two ungrounded conductors landed on the same phase will:",
        "The neutral can carry the sum of both load currents and overheat. Multiwire circuits must be on opposite legs/phases.",
        "Carry the sum of the two load currents and can overheat",
        [
            "Carry zero current because the currents cancel on the same phase",
            "Operate as an equipment grounding conductor",
            "Increase the breaker interrupting rating",
        ],
    ),
    q(
        "hard",
        "A 120-volt load is connected line-to-line on a 240-volt single-phase service by mistake (across two hots). What happens?",
        "The load sees 240 volts and can be destroyed or become a fire hazard. Verify voltage before connecting.",
        "The load is subjected to 240 volts and can be damaged",
        [
            "The load still sees 120 volts because of the neutral",
            "The breaker will always prevent any damage in every case",
            "The equipment grounding conductor will drop the voltage to 120",
        ],
    ),
    q(
        "hard",
        "A control transformer secondary should be fused (or otherwise protected) because:",
        "A shorted coil or wiring can overheat the transformer. Protection is sized to the transformer and conductors, not to 'whatever is in the truck.'",
        "A secondary short can overheat the transformer and wiring",
        [
            "Fusing the secondary prevents all primary shocks",
            "Control transformers cannot produce hazardous voltage",
            "Secondary protection replaces lockout of the line side",
        ],
    ),
    q(
        "hard",
        "Electronic loads with high harmonic content can overheat a shared neutral because:",
        "Triplen harmonics add in the neutral rather than canceling. Neutral current can exceed any phase current. This is why some feeders need an oversized neutral.",
        "Triplen harmonics can add in the neutral instead of canceling",
        [
            "Harmonics cancel all neutral current to zero",
            "Harmonics only affect fiber-optic neutrals",
            "A GFCI always blocks harmonics",
        ],
    ),
    q(
        "hard",
        "A motor circuit includes short-circuit protection and separate overload protection because:",
        "Short-circuit/ground-fault devices clear high-level faults. Overload devices (heaters, dual-element fuses, or electronic overloads) protect from sustained overload. One device may not do both jobs well.",
        "High-level faults and sustained overloads are different duties",
        [
            "Motors never need overload protection if a breaker is present",
            "Overload heaters clear bolted faults faster than any breaker",
            "The equipment grounding conductor provides overload protection",
        ],
    ),
]

INSTALLATION = [
    q(
        "easy",
        "Conductors in a box must have enough free length so that:",
        "There must be sufficient free conductor to make up devices without strain. This is a workmanship and code principle, not a manufacturer quirk.",
        "Splices and devices can be made up without straining the conductors",
        [
            "The box can be overfilled without limit",
            "Insulation can be stripped back to the clamp as a goal",
            "Grounding conductors can be omitted if the box is plastic",
        ],
    ),
    q(
        "easy",
        "NM cable passing through wood studs is protected by:",
        "Steel plates or sufficient setback from the edge so nails do not puncture the cable.",
        "Setback from the edge or nail plates as required",
        [
            "Paint only",
            "Duct tape",
            "Leaving the cable on the face of the stud",
        ],
    ),
    q(
        "easy",
        "A receptacle in a wet location generally needs:",
        "A weather-resistant device and an enclosure/cover suitable for the location (often extra-duty while in use, depending on the installation). Do not use an indoor device outdoors unsheltered.",
        "A device and cover rated for the wet location",
        [
            "An indoor duplex with no cover because rain is grounding",
            "A cardboard cover",
            "No GFCI consideration ever in wet locations",
        ],
    ),
    q(
        "easy",
        "Equipment must be installed with working space in front so that:",
        "A worker can operate and service the equipment safely. Blocking a panel with storage is a common violation of that principle.",
        "A worker can access and operate the equipment safely",
        [
            "The panel can be used as a shelf",
            "Doors can swing into the worker with no path out",
            "The working space can be used as a storage closet",
        ],
    ),
    q(
        "easy",
        "Splices must be made in:",
        "Listed boxes or enclosures with covers, not buried open in plaster or in a wall without access.",
        "An accessible box or listed enclosure",
        [
            "Open wall cavities without a box",
            "Underground without a listed method",
            "Inside a fuel-gas furnace heat exchanger",
        ],
    ),
    q(
        "easy",
        "The grounded (neutral) conductor in typical US AC wiring is identified by:",
        "White or gray is the standard identification for grounded conductors. Green or bare is equipment grounding.",
        "White or gray identification",
        [
            "Green or green with yellow stripe as the preferred neutral",
            "Orange always",
            "Bare copper as the preferred neutral on NM cable",
        ],
    ),
    q(
        "easy",
        "Equipment grounding conductors are typically identified by:",
        "Green, green with yellow stripe, or bare.",
        "Green, green with yellow, or bare",
        [
            "White only",
            "Gray only",
            "Red only",
        ],
    ),
    q(
        "medium",
        "Box fill must be calculated because:",
        "Overfilled boxes overheat, damage insulation, and make devices up unsafely. Count conductors, devices, and fittings as required.",
        "Overfilling can damage insulation and create heat and shock hazards",
        [
            "Boxes are allowed unlimited conductors if the cover goes on",
            "Fill only matters for fiber",
            "Device yokes never count",
        ],
    ),
    q(
        "medium",
        "Torque marks on a breaker lug matter because:",
        "Under-torque causes heating; over-torque damages the lug or conductor. Use a torque tool to the listing.",
        "Correct torque reduces high-resistance heating and damage",
        [
            "Breakers are designed to be tightened until the handle breaks",
            "Torque values are only for automotive work",
            "Aluminum and copper use any random tightness",
        ],
    ),
    q(
        "medium",
        "A continuous load is often calculated at 125% for overcurrent and conductor sizing because:",
        "Continuous operation produces more heat. The 125% factor (where applicable) keeps conductors and devices within temperature limits. Exact applications are in the electrical code; the principle is thermal.",
        "Heat from long-duration current requires extra capacity",
        [
            "Continuous loads produce no heat",
            "125% reduces voltage to the load",
            "The factor replaces equipment grounding",
        ],
    ),
    q(
        "medium",
        "SE cable used as a service-entrance method must be:",
        "Listed, supported, protected from physical damage, and terminated with suitable fittings. Interior routing must follow the rules for the cable type.",
        "Listed for the use, supported, and protected from damage",
        [
            "Stripped of its covering and fished like fixture wire as a standard",
            "Run across a sharp roof edge without protection",
            "Used as a flexible jumper on a motor shaft",
        ],
    ),
    q(
        "medium",
        "A grounding electrode system is intended to:",
        "Connect the electrical system to earth for lightning, surge, and earth-fault reference. It is not a substitute for the equipment grounding conductor that clears faults.",
        "Connect the system to earth; it does not replace the equipment grounding conductor",
        [
            "Carry all normal ungrounded load current",
            "Replace overcurrent devices",
            "Allow omission of EGC to receptacles",
        ],
    ),
    q(
        "medium",
        "When two grounding electrode types are present (for example rod and metal water pipe), they are typically:",
        "Bonded together to form one grounding electrode system so they are not at different potentials.",
        "Bonded together into one grounding electrode system",
        [
            "Left isolated so they cannot interact",
            "Connected only to isolated equipment grounds, never the service",
            "Used as spare neutrals",
        ],
    ),
    q(
        "medium",
        "Kitchen small-appliance branch circuits (where used) are intended to:",
        "Serve receptacle loads in kitchen/dining areas so lighting or other circuits are not overloaded. Exact required numbers are code-edition specific; the principle is dedicated capacity for those loads.",
        "Provide capacity for kitchen/dining receptacle loads rather than sharing randomly with lighting only",
        [
            "Replace the service grounding electrode",
            "Feed only hardwired ranges as their sole use in every dwelling",
            "Be wired with speaker cable",
        ],
    ),
    q(
        "medium",
        "A bathroom receptacle near a basin is commonly GFCI-protected because:",
        "Water and grounded surfaces increase shock risk. GFCI is a personnel-protection practice in wet areas. Specific locations can vary by code edition; the hazard principle is stable.",
        "Water and grounded surfaces increase shock hazard",
        [
            "GFCI increases voltage to hair dryers",
            "Bathroom receptacles cannot be used for portable loads",
            "GFCI replaces the equipment grounding conductor in all bathrooms",
        ],
    ),
    q(
        "medium",
        "Conduit fill is limited so that:",
        "Conductors can dissipate heat and be pulled without damaging insulation. Exceeding fill also makes future pulls destructive.",
        "Heat can dissipate and conductors can be installed without damage",
        [
            "The conduit can be used as a water pipe",
            "Fill limits only apply to fiber",
            "More conductors always cool each other",
        ],
    ),
    q(
        "medium",
        "A disconnecting means for a motor or appliance should be located so that:",
        "A worker can shut off the equipment. Within sight is a common requirement for many motors/appliances; the principle is ready isolation.",
        "The equipment can be isolated for service, often within sight",
        [
            "It is hidden in a locked remote closet with no identification",
            "It only opens the equipment grounding conductor",
            "It is the utility meter’s potential tap",
        ],
    ),
    q(
        "medium",
        "Cable clamps and connectors must be listed for the cable because:",
        "An unlisted clamp can cut insulation or fail to provide strain relief and grounding continuity on metal boxes.",
        "They provide strain relief and must not damage the cable",
        [
            "Any hose clamp is listed for NM cable",
            "Clamps are optional if the sheath is stripped long",
            "Plastic boxes require metal AC-cable connectors as the only method",
        ],
    ),
    q(
        "medium",
        "Identifying a spare or unnamed circuit in a panel is important because:",
        "Future work and emergencies require accurate directories. 'Lighting' on every breaker is not identification.",
        "Accurate circuit directories support safe isolation later",
        [
            "Directories are only for the utility’s billing software",
            "Unidentified breakers are safer because nobody will turn them off",
            "Markers are prohibited on residential panels",
        ],
    ),
    q(
        "hard",
        "A feeder is installed in a hot attic. Why might ampacity need adjustment?",
        "Elevated ambient temperature and bundling reduce allowable current. Use correction/adjustment factors from the electrical code rather than the 30°C column blindly.",
        "High ambient temperature and grouping can reduce allowable current",
        [
            "Attics always increase ampacity because heat thins copper",
            "Ampacity is independent of temperature",
            "Only underground feeders ever need adjustment",
        ],
    ),
    q(
        "hard",
        "A metal water pipe is used as a grounding electrode. A dielectric union is later installed for plumbing reasons. What electrical issue can appear?",
        "The electrode or bonding path can be opened. Bonding jumpers around insulating fittings may be required so the electrical system remains connected to the electrode and metal piping is not left unbonded.",
        "The grounding/bonding path may be interrupted and may need a jumper",
        [
            "Dielectric unions always improve fault clearing",
            "Plumbing changes cannot affect electrical safety",
            "The union replaces the need for an equipment grounding conductor",
        ],
    ),
    q(
        "hard",
        "A service with a high available fault current requires overcurrent devices with adequate interrupting rating because:",
        "If the available fault exceeds the device’s AIC, the device can explode or fail to clear. Match interrupting ratings (or series ratings) to the available current.",
        "The device must be able to safely clear the available fault current",
        [
            "Interrupting rating only needs to exceed the load FLA",
            "Any 10 kA breaker is adequate on every service",
            "Grounding electrodes reduce available fault current to zero",
        ],
    ),
    q(
        "hard",
        "When installing a separately derived generator with a bonded neutral at the generator, the transfer equipment must:",
        "Avoid paralleling neutrals incorrectly. A four-pole switched-neutral transfer (or equivalent design) is used when both sources have bonded neutrals so that objectionable current and multiple bonds do not occur. Follow the system design; do not add a second bond casually at the downstream panel.",
        "Switch the neutral (or otherwise prevent paralleled bonds) according to the grounding scheme",
        [
            "Always solid-neutral transfer with two bonded sources as a universal rule",
            "Disconnect the equipment grounding conductor during transfer as a standard",
            "Bond generator frame to the utility hot as a substitute transfer",
        ],
    ),
    q(
        "hard",
        "A rooftop HVAC unit’s disconnect is installed so it can be opened while standing on wet roofing next to unguarded edges. What installation principles are in conflict?",
        "Electrical working space, weather, and fall protection all apply. Relocate or protect the disconnect so it can be operated without an unnecessary fall or shock hazard.",
        "The disconnect must be usable without forcing a fall or wet-shock hazard",
        [
            "Rooftop equipment is exempt from working-space and fall concerns",
            "Wet roofing makes panels safer",
            "A disconnect is optional if the thermostat can be set to off",
        ],
    ),
]

DIAGNOSTICS = [
    q(
        "easy",
        "A receptacle has no power. Nearby receptacles on the same wall work. What should be checked early?",
        "A tripped GFCI, an open downstream feed, or a bad device. Check GFCI reset and voltage at the device before replacing the service panel.",
        "GFCI devices that may feed it, and voltage at that receptacle",
        [
            "The utility substation first",
            "The grounding electrode rod length first",
            "The transformer turns ratio first",
        ],
    ),
    q(
        "easy",
        "A lighting circuit is dead. The breaker is on. What is a logical next measurement?",
        "Verify voltage at the breaker terminals, then at the first device. A tripped GFCI, open splice, or failed breaker can all present as a dead circuit.",
        "Voltage at the breaker and then at the first device in the circuit",
        [
            "Megger the utility primary as the first residential step",
            "Replace the grounding electrode",
            "Add a larger unlisted fuse at the fixture",
        ],
    ),
    q(
        "easy",
        "A motor hums but does not start. What should be considered early?",
        "Mechanical lock, failed start component, or single-phasing. Do not keep resetting a breaker without investigation.",
        "Whether the load is locked, start components have failed, or a supply phase is missing",
        [
            "Whether the equipment grounding conductor is too long as the usual cause of humming",
            "Whether the device is unlisted for color",
            "Whether the nameplate is in metric",
        ],
    ),
    q(
        "easy",
        "A GFCI receptacle will not reset. What is a sound first check?",
        "A standing ground fault on the load side, line/load reversed, or a failed device. Remove load-side connections and retry before condemning the entire panel.",
        "Whether a load-side fault exists or line/load leads are reversed",
        [
            "Whether the water heater anode is spent",
            "Whether the service drop is aluminum",
            "Whether the panel directory uses pencil",
        ],
    ),
    q(
        "easy",
        "Lights dim when a compressor or well pump starts. What is a likely electrical explanation?",
        "Voltage drop from inrush on a high-impedance supply path. Investigate connections, conductor size, and source capacity—not a smaller breaker.",
        "Voltage drop from starting current on a weak or high-resistance supply path",
        [
            "A GFCI that is too sensitive to light",
            "An AFCI that increases voltage",
            "A grounding rod that is too short as the usual lighting cause",
        ],
    ),
    q(
        "easy",
        "A three-way lighting circuit works from one switch but not the other. What is a common issue?",
        "A traveler is open or misidentified. Confirm travelers and common terminals rather than replacing the fixture first.",
        "An open or miswired traveler or common terminal",
        [
            "A missing grounding electrode as the usual three-way symptom",
            "A water-logged expansion tank",
            "A failed water-heater T&P valve",
        ],
    ),
    q(
        "easy",
        "A breaker trips immediately when turned on, with nothing plugged in. What does that suggest?",
        "A short or ground fault on the circuit conductors or a failed device already connected. Do not keep resetting; isolate and find the fault.",
        "A short or ground fault on the circuit",
        [
            "A normal inrush that should be ignored",
            "That the breaker is definitely too small for 14 AWG as the only explanation",
            "That the utility voltage is too low as the usual immediate-trip cause",
        ],
    ),
    q(
        "medium",
        "Voltage is 120 V with no load at a receptacle but sags to 95 V when a heater is plugged in. What should be investigated?",
        "High-resistance connections, undersized conductors, or a poor backstab. Measure voltage at the panel under the same load to localize.",
        "High-resistance connections or an undersized/poor path in that circuit",
        [
            "A utility overvoltage as the usual sag explanation",
            "A missing blank in the panel dead-front as the usual sag explanation",
            "A white conductor that was reidentified correctly",
        ],
    ),
    q(
        "medium",
        "A motor runs hot at about nameplate FLA. Supply voltage is 10% low. What is a likely contributor?",
        "Low voltage increases current for many motors and reduces cooling effectiveness. Correct the voltage problem before replacing the motor.",
        "Low supply voltage causing extra current and heat",
        [
            "High voltage as the measured 10% low condition",
            "A grounding electrode that is too conductive",
            "A GFCI on a lighting circuit in another building",
        ],
    ),
    q(
        "medium",
        "An AFCI breaker trips when a vacuum cleaner is used, but a standard breaker did not. What is a reasonable approach?",
        "Verify the AFCI is listed and connected correctly, then determine whether the vacuum is producing an arc signature or the circuit has a real arcing fault. Do not replace AFCI with a standard breaker as a 'repair.'",
        "Confirm wiring and whether a real arc-fault or a problematic load signature is present",
        [
            "Replace the AFCI with a higher-amp standard breaker",
            "Remove the equipment grounding conductor to stop trips",
            "Tape the breaker handle on",
        ],
    ),
    q(
        "medium",
        "A customer reports a tingle from a washing machine. What should be done first?",
        "Treat it as a shock hazard: take the equipment out of service, then check grounding/bonding and leakage/fault current. Do not tell the customer to keep using it with shoes on.",
        "Take the appliance out of service and investigate grounding and leakage",
        [
            "Advise standing on a wet floor for a better ground",
            "Remove the equipment grounding conductor so it cannot tingle",
            "Install a larger ungrounded conductor only",
        ],
    ),
    q(
        "medium",
        "A three-phase motor is tripping on overload after a recent reconnect. Rotation is wrong and current is unequal. What should be verified?",
        "Phase sequence, tap configuration, and connections. Unequal current can be a lost phase or a misconnect. Do not upsize overloads to hide it.",
        "Phase connections, supply phases, and overload settings versus nameplate",
        [
            "Whether the grounding rod is copper-coated",
            "Whether the disconnect handle is red or black",
            "Whether NM cable was used on the 5 kV utility line",
        ],
    ),
    q(
        "medium",
        "A fluorescent or LED fixture hums and flickers after a ballast/driver replacement. Voltage is normal. What should be checked?",
        "Incompatible dimmer, failed driver, poor lampholders, or a shared-neutral issue. Replacing the panel is not the first step.",
        "Driver/ballast compatibility, dimming controls, and connections",
        [
            "The water-heater dip tube",
            "The building sewer slope",
            "The closet-flange wax ring",
        ],
    ),
    q(
        "medium",
        "A circuit reads 120 V hot-to-neutral and 120 V hot-to-ground, but 80 V neutral-to-ground under load. What does this suggest?",
        "A high-resistance neutral path can lift the neutral. Investigate the grounded conductor connections. This can damage 120-volt loads on a multiwire circuit.",
        "A poor neutral connection causing the grounded conductor to shift under load",
        [
            "A perfect circuit with no further checks",
            "A utility overvoltage on the grounding electrode only",
            "A GFCI that is working normally as the only explanation",
        ],
    ),
    q(
        "medium",
        "Which situation is inappropriate for insulation-resistance (megger) testing?",
        "High test voltage can damage solid-state equipment and some surge devices, and a live circuit must never be meggared. Isolate sensitive devices and prove the circuit de-energized first.",
        "A live circuit, or equipment that can be damaged by the test voltage unless isolated",
        [
            "De-energized motor windings that are isolated and suitable for the test",
            "A disconnected piece of NM cable with devices removed",
            "An empty spare conduit",
        ],
    ),
    q(
        "medium",
        "A heat pump outdoor unit has 240 V at the disconnect but 0 V at the contactor line side. What is a likely path issue?",
        "Fuses, a whip, or a local switch between disconnect and unit. Measure along the path rather than replacing the compressor.",
        "An open in the conductors or fuses between the disconnect and the contactor",
        [
            "A failed thermostat battery as the source of 240 V",
            "A missing grounding electrode rod as the usual open",
            "A water-logged expansion tank",
        ],
    ),
    q(
        "medium",
        "Nuisance GFCI trips on a circuit with a snow-melt or long outdoor run may be caused by:",
        "Leakage from moisture, damaged insulation, or cumulative leakage of many loads. Find the leakage; do not replace GFCI with a standard receptacle in a location that requires GFCI.",
        "Leakage from moisture, damaged insulation, or accumulated load leakage",
        [
            "A perfectly dry, undamaged circuit as the usual cause",
            "Too large an equipment grounding conductor as the usual cause",
            "Correct torque on lugs as the usual cause",
        ],
    ),
    q(
        "medium",
        "A customer’s lights went bright and dim on different circuits, then some devices failed. What is a classic cause?",
        "A lost utility or service neutral can impress abnormal voltages on 120-volt legs. This is an emergency: unstable voltages can destroy equipment and start fires. Investigate the grounded conductor at the service/utility.",
        "An open incoming neutral causing the 120-volt legs to shift",
        [
            "A GFCI in a bathroom as the usual whole-house brightness swing",
            "An AFCI that is too new",
            "A dimmer on a single lamp as the usual house-wide cause",
        ],
    ),
    q(
        "medium",
        "A clamp meter on a bundled NM cable reads near zero with the load on. Why?",
        "Equal and opposite currents in hot and neutral cancel in the clamp window. Clamp a single conductor.",
        "Hot and neutral currents cancel when both are inside the clamp",
        [
            "The circuit is definitely de-energized",
            "Clamp meters cannot read 60 Hz",
            "The grounding conductor carries all the load current in a healthy circuit",
        ],
    ),
    q(
        "hard",
        "A 208Y/120-volt panel has 208 V between phases, 120 V A-N and B-N, but 208 V C-N. What is a coherent interpretation?",
        "Phase C may be open and backfed through loads, or a high-impedance connection exists on C-N. Do not energize sensitive 120-volt loads on C until the unbalance is explained. Measure at the source and at the lugs.",
        "Phase C’s connection to the source/neutral is not intact; investigate that path before loading it",
        [
            "This is normal for a wye and needs no investigation",
            "The grounding electrode is too long",
            "Replace all A-phase breakers first",
        ],
    ),
    q(
        "hard",
        "A motor trips its overload after running 20 minutes, not at start. Supply voltage is stable and rotation is correct. What should be evaluated?",
        "Mechanical overload, high ambient, dirty cooling fins, overlapping starts, or an overload heater mismatch. Starting components are less likely if it starts and runs for 20 minutes.",
        "Mechanical load, cooling, ambient, and overload-heater selection",
        [
            "Only the start capacitor, because overloads never trip from mechanical load",
            "Utility frequency as the first residential 60 Hz concern",
            "The color of the disconnect handle",
        ],
    ),
    q(
        "hard",
        "Intermittent operation of a feeder coincides with heat on a lug that is discolored. What is the correct priority?",
        "A high-resistance connection is a fire hazard. De-energize, repair the termination, and inspect conductor damage. Do not keep resetting a breaker into a glowing lug.",
        "De-energize and repair the high-resistance termination before further loading",
        [
            "Apply more load to burn the connection clean",
            "Spray water on the lug while energized to cool it",
            "Increase breaker size so it cannot trip",
        ],
    ),
    q(
        "hard",
        "A listed surge-protective device has failed open after a storm, and some electronics died. Service voltage is now normal. What should be checked besides replacing the SPD?",
        "Look for a damaged grounded conductor, loose service connections, and other surge paths. Replacing only the SPD without inspecting the service can leave a degraded neutral or damaged insulation in place.",
        "Service/neutral connections and other damage from the surge event",
        [
            "Only the bathroom GFCI, because surges only enter there",
            "The water-heater anode as the surge path of record",
            "Whether NM sheath color matches the paint",
        ],
    ),
    q(
        "hard",
        "A 480-volt VFD-driven motor has bearing failures and the EGC shows electrical noise. What is a recognized concern to evaluate?",
        "VFD common-mode voltages can pass through motor bearings. Shaft grounding, proper cabling, and manufacturer-recommended filters are typical mitigations—not removing the EGC.",
        "Common-mode voltage from the drive affecting motor bearings; follow the drive maker’s grounding and mitigation methods",
        [
            "Removing the equipment grounding conductor to reduce noise",
            "Replacing the VFD output with NM cable as a universal fix",
            "Bonding the motor shaft to a hot phase",
        ],
    ),
]

CATEGORIES = [
    {
        "slug": "safety_tools_work_practices",
        "name": "Safety, Tools & Work Practices",
        "description": "Electrical safety, tools, and professional work practices.",
        "prefix": "ELEC-SAF",
        "questions": SAFETY,
    },
    {
        "slug": "electrical_theory",
        "name": "Electrical Theory",
        "description": "Voltage, current, resistance, power, and magnetic fundamentals.",
        "prefix": "ELEC-THY",
        "questions": THEORY,
    },
    {
        "slug": "wiring_circuits_components",
        "name": "Wiring, Circuits & Components",
        "description": "Branch circuits, devices, and electrical components.",
        "prefix": "ELEC-CIR",
        "questions": CIRCUITS,
    },
    {
        "slug": "installation_code_fundamentals",
        "name": "Installation & Code Fundamentals",
        "description": "Broadly applicable installation and electrical-code principles.",
        "prefix": "ELEC-INS",
        "questions": INSTALLATION,
    },
    {
        "slug": "troubleshooting_diagnostics",
        "name": "Troubleshooting & Diagnostics",
        "description": "Systematic electrical diagnosis.",
        "prefix": "ELEC-DIAG",
        "questions": DIAGNOSTICS,
    },
]

ASSESSMENT = {
    "slug": "electrical_knowledge",
    "title": "Electrical Knowledge Assessment",
    "description": "A knowledge assessment of electrical safety, theory, circuits, installation, and diagnostics. Scores are not a license or certification.",
    "trade_type": "Electrician",
    "company_disclaimer": None,
    "active": True,
    "position": 3,
    "public_result_rule": "best_valid",
}
