from .common import q

SAFETY = [
    q(
        "easy",
        "Before servicing a rooftop unit, what is the safest first action for the electrical supply?",
        "De-energize the circuit, apply lockout/tagout, and verify the absence of voltage with a meter before contacting conductors or components.",
        "Lock out the disconnect and verify the circuit is de-energized with a meter",
        [
            "Open the access panel and start tracing wires while the unit is still powered",
            "Remove the thermostat batteries so the unit cannot call",
            "Close the gas valve and assume the electrical circuit is also isolated",
        ],
    ),
    q(
        "easy",
        "Why must refrigerants be recovered instead of vented when a system is opened for repair?",
        "Venting most refrigerants is prohibited. Recovery protects the environment and is required before opening the sealed refrigerant circuit.",
        "Releasing refrigerant to the atmosphere is prohibited; it must be recovered into approved cylinders",
        [
            "Venting is faster and is acceptable if the charge is small",
            "Refrigerant can be dumped into the condensate drain if it is mixed with water",
            "Only flammable refrigerants need to be recovered",
        ],
    ),
    q(
        "easy",
        "What personal protective equipment is most important when cutting sheet metal or grinding?",
        "Eye and face protection prevent common, serious injuries from metal fragments. Hearing and hand protection may also be needed, but eyes are the first priority for cutting and grinding.",
        "Safety glasses or a face shield rated for impact",
        [
            "A cotton shop rag tied over the face",
            "Sunscreen and a hat only",
            "Leather welding sleeves without eye protection",
        ],
    ),
    q(
        "easy",
        "When using a portable ladder, which practice is safest?",
        "Maintain three points of contact and set the ladder on stable footing. Overreaching and standing on the top cap are common causes of falls.",
        "Keep three points of contact and do not stand on the top cap or top step",
        [
            "Lean the ladder on a gutter and stand on the top cap to reach farther",
            "Have a coworker bounce the base to walk the ladder closer to the work",
            "Place the ladder on a wet coil box lid to gain height",
        ],
    ),
    q(
        "easy",
        "Where should a technician look first for hazard information about a chemical used on the job?",
        "The Safety Data Sheet (SDS) is the standard source for hazards, PPE, first aid, and spill response.",
        "The Safety Data Sheet (SDS) for that product",
        [
            "The equipment installation sticker only",
            "A coworker’s memory of a similar product",
            "The customer’s homeowner warranty packet",
        ],
    ),
    q(
        "easy",
        "A belt-driven blower must be inspected. What should be done before removing the belt guard?",
        "Moving belts and pulleys are pinch-point hazards. Lock out power and verify the blower cannot start before removing guards.",
        "Lock out power and verify the blower cannot start",
        [
            "Remove the guard quickly while the blower coasts to a stop",
            "Hold the belt with a rag while the motor is still energized",
            "Bypass the door switch so the blower can be observed running without the guard",
        ],
    ),
    q(
        "easy",
        "Why is fall protection a concern on a typical residential or light-commercial rooftop?",
        "Unprotected roof edges, wet surfaces, and skylights create fall hazards. Plan access, stay away from edges, and use required fall protection.",
        "Unprotected roof edges, wet surfaces, and skylights can cause serious falls",
        [
            "Rooftop work is exempt from fall awareness because units are low",
            "Fall protection is only needed if the unit is running",
            "A tool belt is sufficient fall protection",
        ],
    ),
    q(
        "medium",
        "A system must be pressure-tested after a repair. Which gas is the appropriate choice for a dry pressure test?",
        "Dry nitrogen, regulated to a safe test pressure, is the standard pressure-test gas. Oxygen, compressed air with moisture, and unregulated cylinder pressure are unsafe or contaminating.",
        "Dry nitrogen supplied through a regulator set to a safe test pressure",
        [
            "Oxygen from a cutting torch cylinder to raise pressure faster",
            "Unregulated nitrogen straight from the cylinder valve",
            "Acetylene because it is lighter than air and finds leaks quickly",
        ],
    ),
    q(
        "medium",
        "When recovering refrigerant, why must a recovery cylinder not be filled to the top?",
        "Liquid refrigerant expands with temperature. Overfilling can rupture a cylinder. Stay within the cylinder’s rated fill limit, commonly about 80% by volume.",
        "Leaving vapor headspace prevents hydrostatic rupture as temperature rises",
        [
            "A completely full cylinder recovers refrigerant faster",
            "Cylinders are designed to be liquid-packed with no vapor space",
            "Overfilling is acceptable if the cylinder is stored in the shade",
        ],
    ),
    q(
        "medium",
        "Why is a nitrogen purge used while brazing refrigerant piping?",
        "Flowing dry nitrogen during brazing displaces oxygen and reduces copper oxide scale inside the pipe, protecting the compressor and metering device.",
        "It reduces internal oxidation (scale) that can contaminate the system",
        [
            "It increases joint temperature so the braze flows more easily",
            "It replaces the need for a later leak test",
            "It is used only to make the flame burn quieter",
        ],
    ),
    q(
        "medium",
        "A disconnect is open, but the technician has not yet verified voltage. What should be done next?",
        "An open handle does not prove isolation. Use live-dead-live: prove the meter on a known live source, measure the load-side conductors, then prove the meter on a known live source again. Never trust the handle alone.",
        "Prove the meter on a known live source, test the load side, then prove the meter live again",
        [
            "Begin work because an open disconnect is always de-energized",
            "Remove the thermostat only; that isolates line voltage",
            "Touch the conductor with the back of the hand to confirm it is dead",
        ],
    ),
    q(
        "medium",
        "How should refrigerant cylinders be stored on a service truck?",
        "Store cylinders upright, secured against tipping, away from heat sources, and with valves protected. Horizontal storage of liquid-service cylinders and unsecured loads are unsafe.",
        "Upright, secured, valve-protected, and away from heat sources",
        [
            "On their sides under the seat so they stay cool",
            "Loose in the bed so they can be unloaded quickly",
            "Inside the occupied cab with the valves open to equalize pressure",
        ],
    ),
    q(
        "medium",
        "A technician working a hot attic begins to feel dizzy and nauseated. What is the safest immediate action?",
        "Heat illness can escalate quickly. Stop work, move to a cooler area, hydrate, and get help. Continuing work or taking salt tablets without evaluation is unsafe.",
        "Stop work, move to a cooler area, and get assistance",
        [
            "Finish the brazing job first so the system is not left open",
            "Drink an energy drink and continue at a faster pace to finish sooner",
            "Take extra salt tablets and remain in the attic until the job is done",
        ],
    ),
    q(
        "medium",
        "When brazing near combustible building materials, which control is most appropriate?",
        "A fire watch, shielding, and a suitable extinguisher are required when open flame is used near combustibles. Water on electrical equipment or leaving the site immediately after the last braze is not adequate.",
        "Shield combustibles, keep an extinguisher ready, and watch the area after the flame is out",
        [
            "Spray water into the electrical control box to pre-wet it",
            "Leave as soon as the last joint is made; residual heat is never a risk",
            "Increase oxygen flow so the braze is finished before materials can ignite",
        ],
    ),
    q(
        "medium",
        "Why must gauges and hoses be rated for the refrigerant and pressure of the system being serviced?",
        "High-pressure refrigerants such as R-410A can exceed the rating of older R-22 gauges and hoses, creating a rupture and injury hazard.",
        "Underrated gauges or hoses can fail under the system’s operating or standing pressure",
        [
            "Color-matched hoses recover refrigerant faster regardless of rating",
            "Any manifold can be used if the valves are opened slowly",
            "Low-pressure gauges are preferred because they are more accurate at high pressure",
        ],
    ),
    q(
        "medium",
        "A crawlspace has a fuel-fired appliance and limited ventilation. What hazard should the technician consider before extended work?",
        "Confined or poorly ventilated spaces can accumulate combustion gases, refrigerant, or oxygen-deficient air. Assess atmosphere, ventilation, and egress before extended work.",
        "Possible oxygen deficiency or accumulation of combustion products or refrigerant",
        [
            "Crawlspaces are always safe if a flashlight works",
            "Only noise exposure is a concern in crawlspaces",
            "Ventilation is unnecessary if the technician works quickly",
        ],
    ),
    q(
        "medium",
        "What is the correct action if a refrigerant cylinder’s relief device is damaged or the cylinder is visibly bulging?",
        "A compromised cylinder is a pressure vessel failure risk. Do not use it. Isolate it, keep heat away, and follow supplier/hazmat procedures.",
        "Do not use it; isolate it from heat and follow the supplier’s emergency guidance",
        [
            "Hammer the valve to reseat the relief device",
            "Fill it completely so liquid cushions the damaged relief",
            "Warm it with a torch to restore roundness, then continue service",
        ],
    ),
    q(
        "medium",
        "Before using a torch, which check is part of safe setup?",
        "Inspect hoses, connections, reverse-flow protection, and regulator condition. Light with an approved striker, not a cigarette lighter in an uncontrolled way, and never use oil on oxygen equipment.",
        "Inspect hoses, fittings, and regulators for damage and leaks",
        [
            "Crack the oxygen valve and check for leaks with oil-coated hands",
            "Light the torch with a gasoline-soaked rag for a hotter start",
            "Disable flashback arrestors because they slow gas flow",
        ],
    ),
    q(
        "medium",
        "A technician must work on a unit that can be started from a thermostat, a building control, and a service disconnect. What is the key lockout principle?",
        "All energy sources and start paths that can energize the equipment must be isolated and verified. Locking only the thermostat does not control line voltage.",
        "Isolate and verify every energy source that can start or energize the equipment",
        [
            "Lock the thermostat cover; line voltage cannot start the equipment without a call",
            "Tag the unit only; physical locks are optional on residential equipment",
            "Remove one fuse and leave the other leg hot for lighting",
        ],
    ),
    q(
        "hard",
        "A packaged rooftop unit is fed by three-phase power, has a 24-volt control circuit, and a gas supply. What is the safest isolation sequence before opening the blower section?",
        "Control power, line voltage, and fuel are separate energy sources. Shut down, lock and tag the electrical disconnect, verify absence of voltage, and isolate fuel if work could release gas or if burners could fire. Do not rely on a thermostat off switch.",
        "De-energize and lock the electrical disconnect, verify no voltage, and isolate fuel if burner operation is possible",
        [
            "Turn the thermostat to OFF and immediately remove the blower access panel",
            "Close the gas valve only; electricity cannot run a gas-pack blower",
            "Pull the condensate float switch wire so the unit cannot call for heat",
        ],
    ),
    q(
        "hard",
        "When working with a mildly flammable (A2L) refrigerant, which practice is appropriate?",
        "A2L refrigerants require ignition-source control, good ventilation, leak checking, and manufacturer/safe-handling procedures. They are not treated as nonflammable R-410A look-alikes, and they must not be vented.",
        "Control ignition sources, ventilate the work area, and follow the equipment and refrigerant handling procedures",
        [
            "Treat A2L refrigerants exactly like nonflammable R-410A with no extra controls",
            "Vent a small A2L charge outdoors to speed the repair",
            "Use an open-flame leak detector as the primary method because the dye is hard to see",
        ],
    ),
    q(
        "hard",
        "A nitrogen cylinder is being used for brazing purge and pressure testing. Which setup is required?",
        "Cylinder pressure must be reduced with a regulator. A relief or downstream pressure control appropriate to the application is required. Never connect an unregulated cylinder to a system or braze purge line.",
        "A pressure regulator (and appropriate relief) so downstream pressure stays within a safe range",
        [
            "A full-open cylinder valve with no regulator so flow is unrestricted",
            "A torch oxygen regulator because any regulator body will work on nitrogen",
            "A cap on the unused hose instead of a regulator",
        ],
    ),
    q(
        "hard",
        "A system contains an unknown refrigerant and oil mix. What should the technician do before recovery and repair?",
        "Identify the refrigerant (and consider oil compatibility) before recovery so the correct recovery equipment, cylinder, and procedures are used. Mixing refrigerants and dumping into an assumed cylinder contaminates the supply and can create unsafe pressures.",
        "Identify the refrigerant and use compatible recovery equipment and a dedicated cylinder",
        [
            "Recover it into an R-22 cylinder because that is the most common leftover gas",
            "Vent the unknown mix and recharge with the refrigerant the nameplate lists",
            "Add a can of the nameplate refrigerant to dilute whatever is in the system",
        ],
    ),
    q(
        "hard",
        "During recovery, the technician notices the recovery cylinder is frosting heavily and pressure is rising toward the cylinder’s rating. What is the safest next step?",
        "Stop and reassess. Overfill, mixing, a blocked path, or pumping liquid against a closed valve can overpressurize a cylinder. Do not continue filling, do not heat the cylinder with a torch, and do not bypass relief devices.",
        "Stop recovery, check fill level and hose routing, and move to a proper empty cylinder if needed",
        [
            "Keep recovering; frost means the cylinder still has plenty of capacity",
            "Heat the cylinder with a torch so pressure equalizes faster",
            "Disable the recovery machine’s high-pressure cutout to finish the job",
        ],
    ),
]

ELECTRICAL = [
    q(
        "easy",
        "In simple terms, what does voltage represent in a circuit?",
        "Voltage is electrical pressure that pushes current through a resistance. Current is flow; resistance opposes flow; power is the rate of energy use.",
        "Electrical pressure that causes current to flow",
        [
            "The flow of electrons through a conductor",
            "Opposition to current flow",
            "The amount of heat a motor can reject",
        ],
    ),
    q(
        "easy",
        "When should a continuity test be performed?",
        "Continuity and resistance checks are made on a de-energized circuit. Measuring ohms on a live circuit can damage the meter and give false readings.",
        "On a de-energized circuit after power is verified off",
        [
            "While the circuit is at full line voltage so the reading is realistic",
            "Only across the utility transformer primary",
            "In parallel with a running compressor",
        ],
    ),
    q(
        "easy",
        "What is the primary job of a contactor in an outdoor condensing unit?",
        "A contactor is a switch that uses a control-voltage coil to connect and disconnect line-voltage loads such as the compressor and condenser fan.",
        "Switch line-voltage power to loads when the control coil is energized",
        [
            "Step 240 volts down to 24 volts",
            "Store extra current for compressor start",
            "Protect the circuit from ground faults like a GFCI",
        ],
    ),
    q(
        "easy",
        "What does a typical HVAC control transformer do?",
        "The control transformer steps line voltage down to a safer, lower control voltage, commonly 24 volts AC, for thermostats and relays.",
        "Reduce line voltage to a lower control voltage",
        [
            "Increase 24 volts to 240 volts for the compressor",
            "Convert refrigerant pressure into a voltage signal",
            "Store energy for the compressor start winding",
        ],
    ),
    q(
        "easy",
        "Why does HVAC equipment include an equipment grounding path?",
        "An equipment grounding conductor provides a low-impedance path for fault current so overcurrent devices can open and exposed metal is less likely to remain energized.",
        "To give fault current a path that helps clear the fault and reduce shock hazard",
        [
            "To carry normal operating current to the compressor",
            "To increase the voltage available at the motors",
            "To keep the thermostat display backlit",
        ],
    ),
    q(
        "easy",
        "What is the purpose of a fuse or circuit breaker feeding an air conditioner?",
        "Overcurrent devices protect conductors and equipment from overload and short-circuit current. They are not a substitute for disconnecting means during service.",
        "Protect the circuit from overcurrent",
        [
            "Raise voltage if the utility supply sags",
            "Store extra current for starting",
            "Convert single-phase power to three-phase power",
        ],
    ),
    q(
        "easy",
        "A residential split system typically uses which combination of voltages?",
        "Line-voltage loads commonly operate at 120/240 volts, while thermostats and many control devices use 24 volts.",
        "Line voltage for motors and 24-volt control for the thermostat circuit",
        [
            "480-volt controls and 24-volt compressors",
            "Battery-only power for the outdoor unit",
            "Line voltage on the thermostat R and C terminals as the normal design",
        ],
    ),
    q(
        "medium",
        "A 24-volt control circuit has a 40-ohm coil. Approximately how much current does the coil draw?",
        "Ohm’s law: I = V / R = 24 / 40 = 0.6 A. This is typical of a small control load.",
        "0.6 ampere",
        [
            "6 amperes",
            "0.06 milliampere",
            "40 amperes",
        ],
    ),
    q(
        "medium",
        "How should a clamp-on ammeter be used to measure current to a compressor?",
        "Clamp around a single current-carrying conductor. Clamping the entire cable (hot and neutral/return together) cancels the magnetic field and reads near zero.",
        "Clamp around one current-carrying conductor only",
        [
            "Clamp around the entire power cable including all conductors",
            "Clamp around the refrigerant suction line",
            "Clamp around the grounding conductor only",
        ],
    ),
    q(
        "medium",
        "A run capacitor in a single-phase compressor circuit is primarily used to:",
        "The run capacitor provides a phase-shifted current to the start (auxiliary) winding while the motor runs, improving torque and efficiency.",
        "Provide a phase shift for the auxiliary winding during running",
        [
            "Increase line voltage to 480 volts",
            "Store refrigerant during the off cycle",
            "Ground the compressor shell during a fault",
        ],
    ),
    q(
        "medium",
        "A technician measures 24 volts at the transformer secondary but 0 volts at thermostat R. What is the most logical early check?",
        "Power leaves the transformer through a fuse, wiring, and sometimes a door or float switch. An open in that path explains voltage at the transformer and none at R. Replacing the compressor first is not logical.",
        "Look for an open fuse, disconnected wire, or open safety in the R circuit",
        [
            "Replace the compressor because it is the largest load",
            "Add refrigerant until 24 volts appears at the thermostat",
            "Reverse the transformer primary taps to boost control voltage",
        ],
    ),
    q(
        "medium",
        "Why can a voltage reading from a high-impedance meter on an open conductor be misleading?",
        "High-impedance meters can show phantom or ghost voltage from capacitive coupling. A low-impedance meter or a known load helps distinguish a real source from a ghost reading.",
        "The meter may display phantom voltage that cannot supply useful current",
        [
            "High-impedance meters never display voltage on open wires",
            "Any displayed voltage always means a solid utility feed",
            "Phantom voltage only occurs on fiber-optic cables",
        ],
    ),
    q(
        "medium",
        "A thermostat is calling for cooling. There is 24 volts from Y to C at the outdoor unit, but the contactor does not pull in. What should be checked next?",
        "Y-to-C voltage at the unit is not the same as voltage across the coil. Measure voltage across the coil terminals while it is supposed to be energized. Only after de-energizing should resistance or continuity be used to check for an open coil. Do not put an ohmmeter on a live 24-volt circuit.",
        "Voltage across the coil terminals; de-energize before any resistance or continuity check",
        [
            "Coil resistance with the 24-volt circuit still energized",
            "The condensate drain slope",
            "The filter-drier for a temperature drop, before checking the coil",
        ],
    ),
    q(
        "medium",
        "What is a practical difference between a relay and a contactor in HVAC equipment?",
        "Contactors are built to switch higher-current line-voltage loads such as compressors. Relays typically switch lighter control or small loads. Both are electrically operated switches.",
        "Contactors are typically used for higher-current line-voltage loads",
        [
            "Relays can switch unlimited compressor current; contactors cannot",
            "Contactors only work on DC; relays only work on AC",
            "There is no current or construction difference; the names are random",
        ],
    ),
    q(
        "medium",
        "A technician needs to know if a fuse is open. The circuit is de-energized. Which method is appropriate?",
        "Lock out power, isolate the fuse from parallel paths as required, then check continuity or resistance. An in-circuit reading can be fooled by a parallel load path. Never measure ohms on an energized fuse.",
        "Isolate the fuse as required, then measure continuity or resistance",
        [
            "Measure resistance across the fuse while the circuit is live",
            "Look for refrigerant oil on the fuse body",
            "Clamp an ammeter around the fuse while power is off and expect full load current",
        ],
    ),
    q(
        "medium",
        "Why are many 24-volt safety devices wired in series with the control circuit?",
        "Series safeties (float switch, limit, rollout, pressure switch) open the control path so the equipment stops when any one safety opens. Parallel wiring would allow the unit to keep running with a safety open.",
        "Any one open safety can interrupt the control path and stop the equipment",
        [
            "Series wiring increases control voltage at the load",
            "It allows the unit to ignore a single open safety",
            "It converts 24 volts to line voltage",
        ],
    ),
    q(
        "medium",
        "A call for cooling requires the indoor blower and the outdoor unit. On a typical 24-volt thermostat, which terminals are commonly involved?",
        "R is power, Y is cooling, G is fan, C is common. W is heating. Knowing the call path is basic electrical troubleshooting.",
        "R, Y, and G (and C for common)",
        [
            "W only",
            "The compressor run capacitor terminals only",
            "The gas valve solenoid terminals only",
        ],
    ),
    q(
        "medium",
        "Voltage at a motor is 240 volts with no load but sags significantly when the compressor tries to start. What does this suggest?",
        "Excessive voltage drop under load points to supply, wiring, connections, or an undersized circuit—not a need to add refrigerant. Investigate the electrical path before condemning the compressor.",
        "High resistance or an inadequate supply path in the power circuit",
        [
            "The system is overcharged and must be recovered immediately",
            "The thermostat anticipator is set too high",
            "The condensate trap is dry",
        ],
    ),
    q(
        "medium",
        "An ECM indoor blower is not running. Line voltage is present at the module. What is a logical next check before replacing the motor?",
        "Many ECM blowers need a control signal (and often 24 volts) in addition to line voltage. Confirm calls, harness, and control voltage before replacing the motor.",
        "Confirm the control signal/harness and any required 24-volt supply to the module",
        [
            "Add a start capacitor across the ECM as if it were a PSC motor",
            "Jump line voltage directly to the communication pins",
            "Reverse the equipment grounding conductor and a power leg",
        ],
    ),
    q(
        "hard",
        "A dual-run capacitor is labeled 35+5 µF. The compressor will not start; the condenser fan runs. Which check is most appropriate?",
        "The larger value typically serves the compressor and the smaller the fan. If the fan runs, the fan section and one winding path may be intact. Measure capacitance (after safe discharge) of the compressor section and check start/run windings rather than replacing the transformer first.",
        "Safely discharge the capacitor and measure the compressor (HERM) microfarad section",
        [
            "Replace the control transformer because 24 volts cannot start a compressor",
            "Increase the refrigerant charge to raise starting torque",
            "Bypass the outdoor fan so all current goes to the compressor",
        ],
    ),
    q(
        "hard",
        "A dual-voltage three-phase motor can be connected for 230 or 460 volts. What must the technician verify before applying power after a motor replacement?",
        "Taps and jumper configuration must match the supply voltage. A 230-volt connection on 460 volts can destroy the motor; a 460-volt connection on 230 volts will not develop proper torque.",
        "The winding tap/jumper configuration matches the available supply voltage",
        [
            "That all three windings are connected in series regardless of supply voltage",
            "That the equipment grounding conductor is left disconnected to avoid circulating current",
            "That two phases are swapped until the nameplate voltage appears on a single winding",
        ],
    ),
    q(
        "hard",
        "On a 240-volt single-phase outdoor unit, the contactor coil is pulled in. Voltage across the two line-side terminals is about 240 volts, but voltage across the two load-side terminals is about 0 volts. What is the most likely explanation?",
        "Line-side 240 volts proves supply is present. With the coil pulled in, 0 volts across the load-side terminals means the contacts are not completing a 240-volt path to the compressor. Confirm voltage at the compressor terminals before condemning the compressor. Do not treat the missing load-side 240 volts as a shorted compressor or an open 24-volt transformer.",
        "The contacts are not closing a complete 240-volt path to the load",
        [
            "The compressor is definitely shorted to ground",
            "The control transformer secondary is open",
            "The indoor thermostat C wire is missing",
        ],
    ),
    q(
        "hard",
        "An outdoor unit has a communicating indoor controller. There is line voltage at the outdoor terminals, but the unit never starts. What is a sound early diagnostic step?",
        "Communicating systems need intact communication wiring, correct polarity/configuration, and often a control module handshake—not just line voltage. Verify communication wiring and status codes before replacing the compressor.",
        "Check communication wiring, configuration, and module status indications",
        [
            "Add a conventional 24-volt Y jump at the outdoor contactor and leave it permanently",
            "Charge the system to nameplate weight before any electrical diagnosis",
            "Remove the equipment ground so communication noise decreases",
        ],
    ),
    q(
        "hard",
        "A compressor hums and trips the breaker in a few seconds. Supply voltage is stable, and the contactor stays pulled in until the breaker opens. What should be evaluated before condemning the compressor as a grounded winding?",
        "Locked-rotor current from a failed start component, a mechanical lock, or a winding issue can all trip a breaker. Discharge and check capacitors, confirm voltage at the terminals during the attempt, and check winding resistances to ground and between terminals. Jumping the breaker or adding refrigerant is not a diagnosis.",
        "Starting components, applied voltage at the compressor terminals, and winding resistance to ground",
        [
            "Install a larger breaker so the compressor can start",
            "Add refrigerant to cushion the pistons",
            "Remove the overload and jump it out of the circuit permanently",
        ],
    ),
]

REFRIGERATION = [
    q(
        "easy",
        "In the vapor-compression cycle, where does the refrigerant absorb heat from the conditioned space?",
        "The evaporator is where liquid/vapor refrigerant absorbs heat and vaporizes at low pressure.",
        "The evaporator",
        [
            "The condenser",
            "The compressor crankcase heater",
            "The liquid-line filter-drier only",
        ],
    ),
    q(
        "easy",
        "Where does the refrigeration cycle reject heat?",
        "The condenser rejects heat as high-pressure vapor desuperheats, condenses, and usually subcools.",
        "The condenser",
        [
            "The evaporator coil only",
            "The indoor return-air filter",
            "The thermostat",
        ],
    ),
    q(
        "easy",
        "What is the compressor’s primary function in the refrigeration cycle?",
        "The compressor raises refrigerant vapor pressure (and temperature) so heat can be rejected in the condenser, and it moves refrigerant through the circuit.",
        "To raise the pressure of refrigerant vapor and circulate it through the system",
        [
            "To convert liquid refrigerant into oil",
            "To drop liquid pressure like a metering device",
            "To dry the air by absorbing moisture into the crankcase",
        ],
    ),
    q(
        "easy",
        "What is the function of a metering device such as a TXV or piston?",
        "The metering device creates the pressure drop between high-side liquid and the low-side evaporator.",
        "To reduce liquid refrigerant pressure entering the evaporator",
        [
            "To increase suction pressure above condensing pressure",
            "To generate 24-volt control power",
            "To store extra refrigerant during the winter",
        ],
    ),
    q(
        "easy",
        "What is superheat?",
        "Superheat is how many degrees a vapor is above its saturation temperature at that pressure. It helps confirm that vapor, not liquid, is returning to the compressor.",
        "The temperature of vapor above the saturation temperature at that pressure",
        [
            "The temperature of liquid below saturation at that pressure",
            "The temperature difference between supply and outdoor air only",
            "The current draw of the compressor in amperes",
        ],
    ),
    q(
        "easy",
        "What is subcooling?",
        "Subcooling is how many degrees a liquid is below its saturation temperature at that pressure. It helps confirm a full liquid column to the metering device.",
        "The temperature of liquid below the saturation temperature at that pressure",
        [
            "The temperature of vapor above saturation at that pressure",
            "The amount of ice on the suction line",
            "The thermostat heating anticipator setting",
        ],
    ),
    q(
        "easy",
        "What is a liquid-line filter-drier intended to do?",
        "A filter-drier removes moisture, acid, and particles that can damage the metering device and compressor.",
        "Trap moisture, acid, and debris in the liquid refrigerant stream",
        [
            "Increase compressor displacement",
            "Replace the need for a vacuum after a repair",
            "Raise evaporator pressure to condensing pressure",
        ],
    ),
    q(
        "medium",
        "A technician uses a pressure-temperature chart at the evaporator. What is being determined?",
        "Saturated temperature at the measured pressure is read from the P-T relationship so superheat or subcooling can be calculated from an actual thermometer reading.",
        "The saturation temperature that corresponds to the measured pressure",
        [
            "The exact outdoor dry-bulb temperature",
            "The blower motor horsepower",
            "The age of the compressor oil",
        ],
    ),
    q(
        "medium",
        "Compared with older R-22 air-conditioning systems, R-410A typically operates at:",
        "R-410A operating pressures are substantially higher than R-22. Service tools must be rated accordingly.",
        "Higher pressures",
        [
            "Much lower pressures in every mode",
            "Identical pressures, which is why gauges are interchangeable without rating checks",
            "A vacuum on the high side during normal cooling",
        ],
    ),
    q(
        "medium",
        "Why must POE oil be handled carefully during service?",
        "Polyolester oil is hygroscopic: it absorbs moisture from air, which can lead to acid and system damage. Minimize open time and keep containers sealed.",
        "It readily absorbs moisture from air",
        [
            "It never mixes with HFC refrigerants",
            "It is a metallic solid at room temperature",
            "It eliminates the need for a filter-drier",
        ],
    ),
    q(
        "medium",
        "Why is a deep vacuum pulled after a system is opened?",
        "Vacuum removes air and moisture (noncondensables and water vapor) that raise head pressure, freeze at the metering device, and form acid.",
        "To remove air and moisture before charging",
        [
            "To add extra oil capacity",
            "To test the thermostat calibration",
            "To increase the nameplate SEER rating",
        ],
    ),
    q(
        "medium",
        "Sensible heat is heat that:",
        "Sensible heat changes a substance’s measurable temperature (dry-bulb). Latent heat is the energy absorbed or released during a phase change—such as refrigerant boiling or condensing, or water evaporating—without a corresponding dry-bulb temperature change. Moisture removal in cooling is one latent effect, not the definition of latent heat.",
        "Changes a substance’s temperature",
        [
            "Only changes a substance’s state, never its temperature",
            "Is produced only by electric heaters",
            "Cannot be measured with a thermometer in air",
        ],
    ),
    q(
        "medium",
        "A common starting airflow target for comfort cooling is about 400 cfm per ton. How should a technician treat this number?",
        "400 cfm/ton is a common starting point, not a law. Actual airflow must match the equipment design, static capability, and application (humidity, heat pumps, furnaces).",
        "As a common starting point that still must be verified against the equipment and application",
        [
            "As a mandatory value for every heat pump and furnace regardless of design",
            "As the outdoor fan airflow, not the indoor blower",
            "As a refrigerant charging chart substitute",
        ],
    ),
    q(
        "medium",
        "What does external static pressure indicate about a ducted system?",
        "External static pressure is the resistance the blower sees from filters, coils, and ducts. High static reduces airflow.",
        "The airflow resistance the indoor blower is working against",
        [
            "The refrigerant condensing pressure",
            "The gas manifold pressure",
            "The thermostat droop in degrees",
        ],
    ),
    q(
        "medium",
        "In heat pump heating mode, the indoor coil acts as the:",
        "The reversing valve directs discharge vapor to the indoor coil so it condenses and rejects heat to the space. The indoor coil is the condenser in heating.",
        "Condenser",
        [
            "Only a metering device",
            "Compressor",
            "Crankcase heater",
        ],
    ),
    q(
        "medium",
        "What is the purpose of outdoor-coil defrost on an air-source heat pump?",
        "Frost on the outdoor coil blocks airflow and heat transfer. Defrost temporarily puts the unit into a cooling-like refrigerant flow so the outdoor coil can melt frost.",
        "To melt frost that blocks outdoor-coil airflow and heat transfer",
        [
            "To freeze the indoor coil on purpose for humidity control",
            "To recover refrigerant into a cylinder",
            "To calibrate the thermostat clock",
        ],
    ),
    q(
        "medium",
        "On a TXV system, which charging approach is commonly used once airflow is confirmed?",
        "TXV systems are commonly charged by subcooling (per manufacturer data). Fixed-orifice systems are commonly approached with superheat. Always follow the equipment charging method.",
        "Charge to the manufacturer’s target subcooling",
        [
            "Charge only until suction pressure equals liquid pressure",
            "Charge by adding refrigerant until the compressor is silent",
            "Charge by frost line to the compressor",
        ],
    ),
    q(
        "medium",
        "During steady cooling, a liquid-line filter-drier is several degrees colder at the outlet than at the inlet. What does that most nearly suggest?",
        "A small, barely measurable difference can be normal. A drop of several degrees means pressure drop and flashing in the drier—evidence of restriction. It does not by itself prove a failed compressor or a dirty indoor filter.",
        "A restriction in the drier",
        [
            "That the drier is working normally by creating a large temperature drop",
            "That the indoor filter is dirty",
            "That the thermostat is miswired",
        ],
    ),
    q(
        "medium",
        "Latent cooling capacity is associated with:",
        "Latent capacity is moisture removal (dehumidification). Sensible capacity is dry-bulb temperature reduction.",
        "Removing moisture from the air",
        [
            "Raising dry-bulb temperature without changing moisture",
            "The compressor’s locked-rotor amperes",
            "The gas valve opening time",
        ],
    ),
    q(
        "hard",
        "A cooling system with a TXV shows high superheat and high subcooling after airflow is confirmed normal. Which problem is most consistent with those two readings together?",
        "High subcooling means liquid is backing up in the condenser; high superheat means the evaporator is starved. That pair points to a restriction in the liquid feed—liquid line, filter-drier, or TXV inlet/screen—not a simple undercharge, which usually lowers subcooling. Localize the restriction with component temperature drop and frost location; do not assume it is always the drier.",
        "A restriction in the liquid feed (line, drier, or TXV inlet)",
        [
            "A simple undercharge with no restriction",
            "A dirty evaporator filter as the only cause",
            "An overcharge with a wide-open metering device as the only cause",
        ],
    ),
    q(
        "hard",
        "A cooling system shows low superheat and low subcooling after indoor airflow has been verified. What is the most appropriate next step?",
        "Low superheat plus low subcooling is not a one-part verdict. Confirm probe and gauge accuracy, then compare compressor pressure lift with metering-device feed and charge. A weak compressor can look similar to an overfeeding meter with little liquid in the condenser. Do not add refrigerant or replace the compressor as the first step.",
        "Re-verify the readings, then evaluate compressor lift together with metering feed and charge",
        [
            "Replace the compressor immediately because those two readings always mean a failed compressor",
            "Add several pounds of refrigerant without measuring because low subcooling always means undercharge only",
            "Bypass the TXV with a piston as the first step",
        ],
    ),
    q(
        "hard",
        "Noncondensable gas is suspected in a recently repaired system. Which operating clue is most consistent, after confirming condenser airflow is good?",
        "Air or nitrogen left in the system raises condensing pressure and can make subcooling appear abnormal. Recovery, evacuation, and recharge are required—not adding more refrigerant to mask high head.",
        "Abnormally high head pressure for the outdoor conditions",
        [
            "Abnormally low head pressure with a cold condenser",
            "A frozen condensate switch",
            "A thermostat that will not display temperature",
        ],
    ),
    q(
        "hard",
        "A zeotropic blended refrigerant has noticeable temperature glide. What should the technician remember when reading a P-T relationship?",
        "Glide means bubble and dew temperatures differ. Superheat and subcooling must use the correct ends of the P-T data (dew for vapor, bubble for liquid) per the refrigerant’s data—not a single old single-compound habit.",
        "Use the correct dew or bubble value from the refrigerant data, not a single old R-22 habit",
        [
            "Ignore P-T data and charge only until the sight glass looks busy",
            "Treat glide as proof the blend has fractionated and must be vented",
            "Average the high-side and low-side pressures and use that as saturation for both coils",
        ],
    ),
    q(
        "hard",
        "A TXV is hunting (suction pressure swinging). Airflow and charge look reasonable. What is a logical next inspection?",
        "TXV hunting can come from an oversized valve, a poorly mounted or uninsulated sensing bulb, a blocked equalizer, or unstable load. Inspect bulb mounting/location/insulation and equalizer piping before replacing the compressor.",
        "Sensing-bulb mounting, insulation, and equalizer line condition",
        [
            "Replace the indoor thermostat first because hunting is a clock problem",
            "Remove the filter-drier permanently to increase liquid velocity",
            "Jump the high-pressure switch so the valve can stabilize",
        ],
    ),
]

EQUIPMENT = [
    q(
        "easy",
        "Where is a disposable air filter typically installed on a ducted residential system?",
        "The filter is placed in the return path ahead of the blower and coil so it protects equipment and the coil from dirt.",
        "In the return-air path before the blower and indoor coil",
        [
            "On the compressor discharge line",
            "Inside the thermostat subbase",
            "On the outdoor fan motor shaft",
        ],
    ),
    q(
        "easy",
        "Why does an indoor condensate drain need slope and a trap where the equipment design requires one?",
        "Condensate must flow away by gravity, and a trap on negative-pressure drain pans prevents air from being pulled through the drain instead of water leaving the pan.",
        "To let water leave the pan and to prevent air from being pulled through the drain",
        [
            "To pressurize the drain so water sprays into the return",
            "To store extra refrigerant oil",
            "To increase static pressure in the supply ducts",
        ],
    ),
    q(
        "easy",
        "A permanent electrical disconnect for an outdoor unit should be located so that:",
        "A disconnect within sight of the equipment lets a technician isolate power at the unit. Exact code details vary, but the service principle is local, visible isolation.",
        "It can be used to isolate power at the equipment during service",
        [
            "It is hidden in a locked closet far from the unit so homeowners cannot find it",
            "It only interrupts the thermostat C wire",
            "It is mounted on the compressor dome",
        ],
    ),
    q(
        "easy",
        "Where should a room thermostat generally be mounted for a representative reading?",
        "Mount on an interior wall away from supply blasts, lamps, kitchens, and direct sun so it senses space temperature, not a local false load.",
        "On an interior wall away from supply air, lamps, and direct sun",
        [
            "Directly above a supply register",
            "On the furnace vestibule door",
            "On an uninsulated exterior wall in full sun",
        ],
    ),
    q(
        "easy",
        "A gas furnace needs an adequate supply of combustion air because:",
        "Burners require oxygen. Starved combustion produces carbon monoxide and poor flame quality. Blocking combustion air is unsafe.",
        "Burners need oxygen to burn fuel cleanly and completely",
        [
            "Combustion air cools the compressor",
            "Combustion air is used to dry the evaporator coil",
            "Combustion air replaces the need for a vent",
        ],
    ),
    q(
        "easy",
        "Why should indoor and outdoor sections of a split system be matched as a designed pair?",
        "Capacity, metering, airflow, and controls are designed together. Random mismatch can cause poor performance, icing, and compressor damage.",
        "Capacity, metering, and airflow are designed to work together",
        [
            "Any indoor coil can be paired with any outdoor unit if the voltages match",
            "Matching only matters for paint color",
            "The indoor section is only a filter box and does not affect capacity",
        ],
    ),
    q(
        "easy",
        "What is the purpose of a Schrader valve core in a service port?",
        "The core is a spring-loaded check that seals the port until a service hose depresses it. Caps still matter because cores can leak.",
        "To seal the service port until a hose depresses the core",
        [
            "To meter refrigerant like a TXV",
            "To ground the suction line",
            "To store oil for the compressor",
        ],
    ),
    q(
        "medium",
        "Why is the suction line insulated on a typical split air conditioner?",
        "Suction insulation reduces unwanted heat gain (which adds load) and limits condensation on the cold vapor line.",
        "To limit heat gain and condensation on the cold vapor line",
        [
            "To keep liquid refrigerant from freezing in the liquid line",
            "To raise discharge temperature",
            "To make the line set easier to bend",
        ],
    ),
    q(
        "medium",
        "What is a condensate overflow (float) switch intended to do?",
        "If the drain backs up, the switch opens the control circuit to stop further condensate production before water damages the structure.",
        "Stop the equipment if the drain pan water level rises too high",
        [
            "Increase blower speed when humidity is high",
            "Add water to the pan to keep the trap primed",
            "Bypass the indoor coil when water is present",
        ],
    ),
    q(
        "medium",
        "Electric heat strips in an air handler are commonly staged because:",
        "Staging limits inrush current and matches heat output to load. Energizing every kW on a small call wastes energy and can trip breakers.",
        "To match heat output to load and limit electrical inrush",
        [
            "To reverse the refrigeration cycle",
            "To dry the liquid-line drier",
            "To start the compressor unloaded",
        ],
    ),
    q(
        "medium",
        "What is the purpose of a crankcase heater on many compressors?",
        "A crankcase heater keeps refrigerant from migrating into the oil during the off cycle, which helps prevent oil dilution and slugging on start.",
        "To keep refrigerant from condensing in the oil during the off cycle",
        [
            "To defrost the indoor coil",
            "To superheat the liquid line",
            "To power the thermostat display",
        ],
    ),
    q(
        "medium",
        "A hard-start kit is typically added to a single-phase compressor to:",
        "A start capacitor and potential relay (or PTC) increase starting torque for hard-start conditions. It is not a substitute for correct charge or voltage.",
        "Increase starting torque under difficult starting conditions",
        [
            "Raise SEER by lowering running amps permanently",
            "Convert the compressor to three-phase power",
            "Replace a failed run capacitor as a permanent repair",
        ],
    ),
    q(
        "medium",
        "On a gas furnace, what is the difference between inlet (supply) gas pressure and manifold pressure?",
        "Inlet pressure is what arrives at the valve. Manifold pressure is the regulated pressure delivered to the burners and must match the appliance rating for the fuel.",
        "Inlet is pressure arriving at the valve; manifold is the regulated pressure to the burners",
        [
            "They are always identical, so only one measurement is ever needed",
            "Manifold pressure is the duct static pressure",
            "Inlet pressure is measured at the evaporator coil",
        ],
    ),
    q(
        "medium",
        "Raising indoor blower speed on a furnace generally does what to temperature rise?",
        "More airflow across the heat exchanger carries away more heat, so temperature rise falls (within design limits). Too little airflow raises rise and can overheat the exchanger.",
        "Temperature rise decreases",
        [
            "Temperature rise always increases",
            "Manifold gas pressure increases automatically",
            "The vent becomes a supply duct",
        ],
    ),
    q(
        "medium",
        "Why is combustion analysis used on a fuel-fired appliance after setup or major service?",
        "Combustion analysis verifies that fuel, air, and venting are producing a safe, complete burn (O2/CO2/CO and, where required, temperature/draft). Visual flame color alone can miss dangerous CO.",
        "To verify safe, complete combustion rather than relying on flame color alone",
        [
            "To measure refrigerant superheat",
            "To set the thermostat heat anticipator in milliseconds",
            "To calculate duct leakage in CFM25",
        ],
    ),
    q(
        "medium",
        "A package unit differs from a split system primarily because:",
        "A package unit contains the evaporator, condenser, and compressor in one outdoor/rooftop cabinet, with duct connections. A split system separates indoor and outdoor sections.",
        "The refrigeration and air-handling components are in one cabinet",
        [
            "Package units never use electricity",
            "Split systems cannot provide cooling",
            "Package units have no fans",
        ],
    ),
    q(
        "medium",
        "On many heat pumps, auxiliary electric heat is used when:",
        "Auxiliary heat supplements the heat pump in cold weather, during defrost, or when the thermostat calls for emergency/supplemental heat. It is not a refrigerant recovery method.",
        "The heat pump cannot meet the load, during defrost, or on an emergency-heat call",
        [
            "The outdoor coil needs extra refrigerant",
            "The compressor is being vacuumed",
            "The condensate pan is dry",
        ],
    ),
    q(
        "medium",
        "A normally closed condensate float switch is typically wired so that:",
        "In the control circuit, a closed float allows 24 volts to pass. Rising water opens the switch and interrupts the call. Wiring it to short R to Y would force cooling with a full pan.",
        "Rising water opens the control circuit and stops the call",
        [
            "Rising water jumps R to Y to force more cooling",
            "The switch feeds line voltage to the compressor independently of the contactor",
            "The switch closes the gas valve to high fire",
        ],
    ),
    q(
        "medium",
        "Line-set length and lift matter on a split system because they affect:",
        "Long lines and lift change pressure drop, oil return, and required charge. Manufacturers specify limits, traps, and extra charge—do not ignore them.",
        "Pressure drop, oil return, and required refrigerant charge",
        [
            "Only the thermostat wire color",
            "Only the filter MERV rating",
            "The utility supply voltage",
        ],
    ),
    q(
        "hard",
        "An induced-draft gas furnace’s inducer runs, but the igniter never energizes and the control reports a pressure-switch fault. What is the most appropriate early check?",
        "If the board never leaves the pressure-switch prove step, the burners should not have lit. Confirm that the inducer develops draft, that the vent/intake and condensate hose are clear, and that the switch actually closes. Jumping the switch permanently, raising manifold pressure, or treating it as a refrigerant problem is unsafe or irrelevant.",
        "Confirm inducer draft, vent/intake path, condensate/hose, and that the switch closes",
        [
            "Replace the indoor TXV because furnace lockout is a refrigerant problem",
            "Jump the pressure switch permanently so the burners can run",
            "Increase manifold pressure well above rating to force a stronger flame",
        ],
    ),
    q(
        "hard",
        "A condensing (high-efficiency) furnace produces acidic condensate from the secondary heat exchanger. What installation implication follows?",
        "Condensate is corrosive and must be handled with compatible materials, a proper drain/trap, and protection against freezing or backing up into the furnace. Using ordinary steel pipe or dumping into a furnace vestibule is wrong.",
        "Drain materials and routing must be compatible with acidic condensate and must not back up into the appliance",
        [
            "The condensate can be ignored because it is distilled water",
            "The secondary exchanger condensate should be routed into the supply duct for humidity",
            "Acidic condensate should be neutralized by mixing it with refrigerant oil in the pan",
        ],
    ),
    q(
        "hard",
        "A ductless mini-split indoor unit does not respond, though line voltage is present at the outdoor unit. What should be verified early?",
        "Mini-splits depend on communication wiring, correct terminal identification, and sometimes a specific interconnect cable. Confirm interconnect wiring and indoor power before replacing the compressor.",
        "Interconnect/communication wiring and power at the indoor unit",
        [
            "That the indoor coil has a conventional 24-volt contactor like a packaged RTU",
            "That R-22 has been added regardless of nameplate refrigerant",
            "That the equipment grounding conductor has been lifted to reduce communication noise",
        ],
    ),
    q(
        "hard",
        "A zoned duct system with a single-speed blower has several zones closed. Supply static is high and the coil is approaching freeze-up. What is a logical system-level concern?",
        "Closing too many zones without a bypass, variable-speed blower, or dump zone can over-restrict airflow. Do not just add refrigerant. Evaluate zone/bypass strategy and minimum airflow.",
        "Airflow may be below the coil’s minimum because too much duct is closed",
        [
            "The compressor needs a larger breaker",
            "The liquid line should be uninsulated to add load",
            "The thermostat C wire should be removed to reduce static",
        ],
    ),
    q(
        "hard",
        "A TXV sensing bulb must be installed so that it:",
        "The bulb should contact the suction line with good metal-to-metal contact, correct orientation for line size, and insulation from ambient air. A loose or uninsulated bulb makes the valve unstable.",
        "Has good thermal contact on the suction line and is insulated from ambient air",
        [
            "Is left hanging in the airstream so it reads room temperature",
            "Is strapped to the liquid line leaving the condenser",
            "Is mounted on the compressor discharge muffler",
        ],
    ),
]

DIAGNOSTICS = [
    q(
        "easy",
        "An evaporator coil is frozen and airflow from the registers is weak. What should the technician check early?",
        "Weak airflow is a leading cause of a frozen evaporator. Check the filter, blower, and duct restrictions before condemning the TXV or adding a large refrigerant charge.",
        "Filter, blower operation, and other indoor airflow restrictions",
        [
            "Replace the compressor as the first step",
            "Add refrigerant until the ice melts",
            "Bypass the float switch so the unit can keep running",
        ],
    ),
    q(
        "easy",
        "A customer reports no cooling. The outdoor unit is silent. What is a reasonable first verification?",
        "Confirm the thermostat mode/setpoint, disconnect, and breaker before opening the sealed system. Many 'no cool' calls are control or power issues.",
        "Thermostat mode/setpoint and whether the unit has electrical power",
        [
            "Recover the entire charge immediately",
            "Replace the indoor coil",
            "Cut the liquid line to see if refrigerant sprays",
        ],
    ),
    q(
        "easy",
        "Indoor unit is running but there is water on the floor beneath the air handler. What should be checked early?",
        "Condensate drain, trap, and pan overflow are the common causes. Do not start with a compressor replacement.",
        "Condensate drain, trap, and pan overflow path",
        [
            "The outdoor fan capacitor only",
            "The gas manifold pressure",
            "The thermostat heat anticipator",
        ],
    ),
    q(
        "easy",
        "A furnace does not start. The thermostat is set to heat and the setpoint is above room temperature. What is a logical next observation?",
        "Confirm a heat call and then watch the ignition sequence (inducer, ignition, proving, blower) rather than replacing random parts.",
        "Whether the furnace is receiving a heat call and how far the ignition sequence proceeds",
        [
            "Recover refrigerant from the furnace coil first",
            "Replace the evaporator coil as a first step",
            "Add a hard-start kit to the indoor blower",
        ],
    ),
    q(
        "easy",
        "The outdoor fan is running and the compressor is running, but the house is not cooling. What measurement helps confirm whether the system is moving heat?",
        "Supply-to-return air temperature difference (and outdoor operation) shows whether the system is actually cooling. Do not add refrigerant without data.",
        "Supply-air to return-air temperature difference",
        [
            "Only the color of the thermostat backlight",
            "Only the age of the air filter printed on the cardboard",
            "The number of fins per inch on the outdoor coil without any temperatures",
        ],
    ),
    q(
        "easy",
        "A rattling noise started after a storm. What is a safe early inspection?",
        "Look for debris, loose panels, and fan obstruction with power locked out. Do not reach into a running fan.",
        "Lock out power and look for debris, loose panels, or a damaged fan",
        [
            "Reach into the running condenser fan to feel for balance",
            "Add refrigerant to dampen vibration",
            "Bypass the high-pressure switch so the unit ignores the noise",
        ],
    ),
    q(
        "easy",
        "Ice is forming on the outdoor suction-line service valve during cooling. What is the most appropriate early diagnostic approach?",
        "Ice on the suction path can come from low airflow, low charge, or a restriction. It does not by itself prove one failed component. Check airflow and then evaluate charge with proper measurements.",
        "Evaluate indoor airflow first, then use superheat/subcooling to judge charge or restriction",
        [
            "Replace the compressor immediately because ice always means a failed compressor",
            "Add refrigerant until the ice melts, without measuring the system",
            "Bypass the low-pressure switch so the unit can keep running",
        ],
    ),
    q(
        "medium",
        "Head pressure is high and the condenser is dirty. What should be done before recovering a large amount of refrigerant?",
        "Dirty condensers cause high head. Clean the coil and re-evaluate against outdoor conditions before deciding the system is overcharged.",
        "Clean the condenser and re-check pressures against outdoor conditions",
        [
            "Recover refrigerant immediately without cleaning",
            "Bypass the high-pressure switch and keep running",
            "Close the liquid service valve to starve the evaporator as a repair",
        ],
    ),
    q(
        "medium",
        "A compressor hums but does not start. Voltage at the unit is normal. What are appropriate early checks?",
        "Start/run capacitors and a mechanical lock are common. Check starting components and current/voltage at the compressor before replacing the thermostat.",
        "Start/run capacitors and whether the compressor is mechanically or electrically locked",
        [
            "The indoor drain trap primer only",
            "The thermostat backlight setting",
            "The MERV rating sticker color",
        ],
    ),
    q(
        "medium",
        "A furnace lights, then shuts down after a few seconds. What should the technician observe next?",
        "Watch whether flame is sensed, whether the inducer/pressure switch stays closed, and whether a limit opens. Cleaning or replacing a flame sensor may be appropriate after confirming the sequence—not jumping safeties.",
        "The ignition sequence and which safety or flame-proving step fails",
        [
            "Jump the rollout and limit switches permanently",
            "Disable the inducer so the flame stays in the cabinet",
            "Add refrigerant to the heat exchanger",
        ],
    ),
    q(
        "medium",
        "A heat pump is calling for heat. Indoor supply air is briefly cool while the outdoor unit is steaming or shedding melt water. What is the most logical interpretation?",
        "Reverse-cycle defrost sends hot gas to the outdoor coil, so that coil can steam while the indoor coil temporarily absorbs heat and supply air feels cool. Many systems also energize auxiliary heat during defrost. Outdoor steaming with cool indoor air is expected during defrost—not a reason to replace the compressor or add charge before confirming mode.",
        "The unit is in reverse-cycle defrost; cool indoor air during outdoor steaming can be normal",
        [
            "Replace the compressor immediately because cool supply air always means a failed compressor",
            "Remove the outdoor coil so it cannot frost",
            "Add refrigerant until the suction line is warm without checking whether the unit is in defrost",
        ],
    ),
    q(
        "medium",
        "A contactor chatters on a cooling call. What is a likely electrical cause to check early?",
        "Chatter is often low control voltage, a loose connection, or a failing coil—not a dirty filter as the first electrical explanation.",
        "Low 24-volt supply or a loose control connection at the coil",
        [
            "A dirty return filter as the only electrical cause",
            "A disconnected condensate cap as the only cause",
            "The color of the liquid-line insulation",
        ],
    ),
    q(
        "medium",
        "The system short-cycles on cooling. What is a sound diagnostic approach?",
        "Short cycling has many causes: oversized equipment, low airflow, safeties, charge, or control issues. Gather runtime, pressures, airflow, and which device opens—do not immediately replace the compressor.",
        "Identify whether a safety, thermostat, airflow problem, or charge issue is ending the cycle",
        [
            "Replace the compressor as the standard first repair",
            "Wedge the contactor closed so it cannot cycle",
            "Remove the low-pressure switch and leave it out",
        ],
    ),
    q(
        "medium",
        "Suction and head pressures are both lower than expected, and indoor airflow is confirmed. What is a reasonable next evaluation?",
        "Low-low pressures with good airflow often point toward undercharge or a starved evaporator from a restriction. Use superheat and subcooling together rather than adding a random amount of refrigerant.",
        "Compare superheat and subcooling to distinguish undercharge from a restriction",
        [
            "Add refrigerant until the sight glass is meaningless on a TXV system without measurements",
            "Replace the indoor blower capacitor first",
            "Close the return so the coil can get colder",
        ],
    ),
    q(
        "medium",
        "An ECM blower does not run on a call, though the furnace board shows a request. What should be checked before replacing the blower?",
        "Harness, control signal, and line voltage at the ECM module are required. Jumping 240 volts onto communication pins can destroy the motor.",
        "Line voltage, module harness, and the control command to the motor",
        [
            "Apply 240 volts directly to the communication pins",
            "Add a PSC run capacitor across the ECM leads as a standard repair",
            "Reverse the grounding conductor and a hot leg",
        ],
    ),
    q(
        "medium",
        "A heat pump outdoor coil ices heavily and defrosts rarely. Outdoor airflow looks blocked by debris. What should happen first?",
        "Restore outdoor airflow (debris, fan, coil cleanliness) before replacing defrost sensors or adding charge. Blocked airflow causes icing.",
        "Clear debris and restore outdoor airflow, then re-evaluate defrost",
        [
            "Disable defrost so the unit stays in heating",
            "Add several pounds of refrigerant to raise outdoor coil temperature",
            "Jump the defrost board to electric heat continuously",
        ],
    ),
    q(
        "medium",
        "A customer reports intermittent cooling. Connections at the contactor are discolored, heat-damaged, and loose. What is the appropriate early repair direction?",
        "Heat-damaged lugs and conductors are a fire and shock hazard. De-energize, replace burned terminals/lugs and any damaged conductor, land on clean metal, and torque to spec. Tightening a burned connection is not a repair. Fix the electrical path before a sealed-system repair.",
        "Replace the burned terminals/conductors as needed, then remake and torque the connections",
        [
            "Only snug the burned lugs and leave the discolored conductor in place",
            "Coat the lugs with refrigerant oil for conductivity",
            "Bypass the contactor with wire nuts as a permanent repair",
        ],
    ),
    q(
        "medium",
        "After a capacitor replacement, the fan runs but the compressor still will not start. What should be verified?",
        "A dual capacitor has separate sections. Confirm the HERM (compressor) section rating and wiring, compressor winding conditions, and voltage—do not assume the new part is automatically the correct section or value.",
        "That the compressor capacitor section, wiring, and compressor windings/voltage are correct",
        [
            "That the thermostat was set to emergency heat",
            "That the suction line is uninsulated on purpose",
            "That the float switch is jumped for testing permanently",
        ],
    ),
    q(
        "medium",
        "Cooling is poor. Delta-T is low, and the evaporator is not that cold. Condenser airflow is good. What pair of measurements should be taken next?",
        "Superheat and subcooling, with airflow already considered, distinguish charge, metering, and compressor problems. Guessing a TXV or adding gas without those readings is poor diagnosis.",
        "Superheat and subcooling (with suction and liquid pressures/temperatures)",
        [
            "Only the thermostat model number",
            "Only the filter brand",
            "Only the color of the wire nuts",
        ],
    ),
    q(
        "hard",
        "Call for cool, 24 volts at the contactor coil, contacts closed, but the compressor is not running. Voltage is present at the compressor terminals. What is the next diagnostic layer?",
        "Power is reaching the compressor, so evaluate windings, overload, mechanical lock, and start components. Do not add refrigerant as an electrical repair, and do not jump an overload as a permanent fix.",
        "Compressor windings, internal overload, and starting components",
        [
            "Add refrigerant to electrically start the motor",
            "Replace the thermostat because Y voltage is already at the coil",
            "Remove the equipment ground to reduce drag",
        ],
    ),
    q(
        "hard",
        "A TXV cooling system has high superheat and high subcooling. Airflow is good. How should the restriction be localized before parts are replaced?",
        "High SH with high SC means the evaporator is starved while liquid is backing up before the restriction. Compare temperature drop across the filter-drier with frost or drop at the TXV, and check bulb mounting and charge. A several-degree drop across the drier implicates the drier; little drier drop with a cold TXV body points to the valve or its inlet screen.",
        "Compare drier inlet-to-outlet temperature drop with TXV bulb mounting, frost location, and valve drop",
        [
            "Replace the compressor first because high subcooling always means a failed compressor",
            "Add refrigerant until subcooling falls, without locating the restriction",
            "Replace the indoor blower motor because airflow was already confirmed good",
        ],
    ),
    q(
        "hard",
        "A gas furnace rollout switch is tripped. What is the correct service approach?",
        "Rollout means flame left the heat exchanger/burner area. Find the cause (blockage, cracked exchanger, overfire, venting) before resetting repeatedly. Repeated resets without diagnosis are unsafe.",
        "Do not keep resetting it; find why flame left the proper path before returning the furnace to service",
        [
            "Reset it as often as needed so the customer has heat tonight without inspection",
            "Jump the rollout switch and raise manifold pressure",
            "Tape the switch closed and clean the evaporator coil instead",
        ],
    ),
    q(
        "hard",
        "A system was topped off repeatedly with whatever refrigerant was on the truck. Performance is poor and pressures do not match the nameplate P-T relationship. What should be done?",
        "A mixed, unknown charge cannot be reliably diagnosed or legally/properly topped off. Recover, determine the correct refrigerant, evacuate, and charge per the manufacturer method.",
        "Recover the mixed charge, evacuate, and recharge with the nameplate refrigerant using the correct method",
        [
            "Keep adding the truck refrigerant until pressures look familiar",
            "Vent the mix and run the system empty to dry it",
            "Add oil only, because mixed refrigerants are harmless",
        ],
    ),
    q(
        "hard",
        "A compressor is noisy and running hot. Suction pressure is high and discharge pressure is low for the conditions, so the compressor is developing little pressure lift. Superheat is low. Gauges and, on a heat pump, reversing-valve position have been confirmed. What is the most consistent compressor concern?",
        "Little pressure difference between suction and discharge with a hot, noisy compressor and a flooded evaporator (low superheat) points to weak compression or internal leakage. Undercharge would usually raise superheat and lower suction pressure. Confirm measurements and reversing-valve seating before condemning the compressor; do not add charge as the repair.",
        "Weak compression or internal leakage through the compressor",
        [
            "A simple undercharge as the only explanation",
            "A dirty filter as the only explanation",
            "A failed thermostat battery as the only explanation",
        ],
    ),
]

CATEGORIES = [
    {
        "slug": "safety_tools_work_practices",
        "name": "Safety, Tools & Work Practices",
        "description": "Jobsite safety, refrigerant handling, tools, and professional work practices.",
        "prefix": "HVAC-SAF",
        "questions": SAFETY,
    },
    {
        "slug": "electrical_fundamentals",
        "name": "Electrical Fundamentals",
        "description": "HVAC electrical theory, controls, and safe electrical troubleshooting.",
        "prefix": "HVAC-ELEC",
        "questions": ELECTRICAL,
    },
    {
        "slug": "hvac_refrigeration_fundamentals",
        "name": "HVAC & Refrigeration Fundamentals",
        "description": "Refrigeration cycle, heat transfer, airflow, and charging fundamentals.",
        "prefix": "HVAC-REF",
        "questions": REFRIGERATION,
    },
    {
        "slug": "equipment_components_installation",
        "name": "Equipment, Components & Installation",
        "description": "Equipment components, installation practices, and setup.",
        "prefix": "HVAC-EQP",
        "questions": EQUIPMENT,
    },
    {
        "slug": "troubleshooting_diagnostics",
        "name": "Troubleshooting & Diagnostics",
        "description": "Systematic diagnosis of comfort cooling and heating problems.",
        "prefix": "HVAC-DIAG",
        "questions": DIAGNOSTICS,
    },
]

ASSESSMENT = {
    "slug": "hvac_knowledge",
    "title": "HVAC Knowledge Assessment",
    "description": "A knowledge assessment of HVAC safety, electrical, refrigeration, equipment, and diagnostics. Scores are not a license or certification.",
    "trade_type": "HVAC Technician",
    "company_disclaimer": None,
    "active": True,
    "position": 1,
    "public_result_rule": "best_valid",
}

