from .common import q

SAFETY = [
    q(
        "easy",
        "Before cutting into a water supply line, what should the technician do first?",
        "Locate and close the correct isolation valves, relieve pressure, and verify the line is depressurized. Cutting a live, pressurized line creates flooding and injury hazards.",
        "Isolate the water, relieve pressure, and verify the line is depressurized",
        [
            "Cut quickly so less water can escape",
            "Open all fixtures to increase pressure, then cut",
            "Heat the pipe with a torch first so water boils away",
        ],
    ),
    q(
        "easy",
        "Why is eye protection required when cutting, soldering, or driving fittings?",
        "Chips, flux, solder splatter, and snapping plastic or copper can injure eyes. Safety glasses are basic PPE for those tasks.",
        "Flying chips, flux, and solder splatter can injure the eyes",
        [
            "Eye protection is only for electrical work",
            "Soldering flux is harmless to eyes by design",
            "A baseball cap is sufficient eye protection",
        ],
    ),
    q(
        "easy",
        "When working in a trench, which action should a technician avoid?",
        "Unprotected trench walls can collapse. Use required cave-in protection, keep spoil back from the edge, and provide a safe way in and out. Do not enter an unprotected deep trench.",
        "Entering an unprotected trench that is deep enough for a cave-in hazard",
        [
            "Keeping excavated soil back from the trench edge",
            "Using a ladder or other safe means of egress",
            "Following the required cave-in protection for the trench",
        ],
    ),
    q(
        "easy",
        "A solvent-cemented PVC joint should be made in a ventilated area because:",
        "Primer and cement vapors are flammable and irritating. Ventilate, avoid ignition sources, and use the product SDS for PPE.",
        "Primer and cement vapors are hazardous and can be flammable",
        [
            "The vapors increase water pressure in the pipe",
            "Cement only works in a sealed, unventilated room",
            "Ventilation makes the joint cure more slowly on purpose",
        ],
    ),
    q(
        "easy",
        "Why must a technician know the difference between a potable-water pipe and a DWV pipe before cutting?",
        "Cutting the wrong system can contaminate drinking water or open a soil pipe. Identify the system by location, markings, and isolation before cutting.",
        "Cutting the wrong system can contaminate drinking water or release sewage",
        [
            "All pipes in a dwelling carry only potable water",
            "DWV and potable lines are interchangeable if the diameter matches",
            "Color of the pipe wrench determines the system",
        ],
    ),
    q(
        "easy",
        "What is the safest way to check for a leak after a soldered copper joint cools?",
        "Pressurize with the appropriate test method and inspect. Do not use an open flame as a leak detector on a water system, and do not leave a joint untested.",
        "Pressurize the system and inspect the joint for leaks",
        [
            "Pass an open flame around the joint to dry any moisture",
            "Hit the joint with a hammer to seat it",
            "Cover the joint with tape so leaks cannot be seen",
        ],
    ),
    q(
        "easy",
        "When lifting a water heater, which practice reduces injury risk?",
        "Use help or mechanical advantage, lift with the legs, and plan the path. Water heaters are heavy and awkward; rushing a one-person lift is a common injury pattern.",
        "Use help or equipment and lift with good body mechanics",
        [
            "Twist at the waist while holding the tank at arm’s length",
            "Walk the tank down stairs without a helper because it is round",
            "Pull the tank by the T&P valve as a handle",
        ],
    ),
    q(
        "medium",
        "A torch is used to solder copper near wood framing. What control is appropriate?",
        "Shield combustibles, keep an extinguisher ready, and watch for smoldering after the flame is out. Water-soaking live electrical boxes or leaving immediately is not adequate.",
        "Shield nearby combustibles and maintain a fire watch after soldering",
        [
            "Increase oxygen so the solder finishes before wood can ignite",
            "Leave as soon as the last joint is made; residual heat is never a risk",
            "Soak nearby electrical devices with water before lighting the torch",
        ],
    ),
    q(
        "medium",
        "Why should a technician confirm that a pipe is not a gas line before cutting what looks like a water pipe?",
        "Gas and water piping can look similar in some installations. Cutting a live gas line is a fire and explosion hazard. Identify the system, isolate, and verify.",
        "A misidentified gas line can release fuel and create a fire or explosion hazard",
        [
            "Gas piping is harmless if the odorant is present",
            "Any metal pipe can be cut first and identified later",
            "Gas lines always use the same insulation as PEX",
        ],
    ),
    q(
        "medium",
        "What is a primary hazard of using a chemical drain cleaner in a fixture the technician will then open?",
        "Chemical cleaners can cause severe chemical burns and react with other products. If a drain must be opened, avoid mixing chemicals and use PPE; mechanical clearing is often safer for the technician.",
        "The chemical can burn skin and eyes and may still be in the pipe",
        [
            "The chemical always makes solder joints stronger",
            "The chemical converts sewage to potable water",
            "The chemical eliminates the need for PPE",
        ],
    ),
    q(
        "medium",
        "When using a drain-cleaning machine, which practice is essential?",
        "Use a properly guarded machine, PPE, and control of the cable. Forcing a spinning cable with loose clothing or bypassing guards causes entanglement injuries.",
        "Keep guards in place, wear PPE, and control the rotating cable",
        [
            "Remove the belt guard so the cable spins faster",
            "Wrap the cable around the forearm for better feel",
            "Wear loose gloves that can catch on the cable",
        ],
    ),
    q(
        "medium",
        "Why is confined-space awareness important in a sewage lift-station pit or similar space?",
        "These spaces can have oxygen deficiency, hydrogen sulfide, or methane. Entry may require atmospheric testing and confined-space procedures—not just a longer job.",
        "The atmosphere may be oxygen-deficient or contain toxic or flammable gases",
        [
            "Pits are always safe if the pump is off",
            "Sewage gases are harmless because they smell",
            "A paper dust mask is complete confined-space protection",
        ],
    ),
    q(
        "medium",
        "Lead-containing solder is not used on potable water piping because:",
        "Lead can leach into drinking water. Potable joints use lead-free solder/alloys and listed materials. This is a health requirement, not a cosmetic preference.",
        "Lead can contaminate drinking water",
        [
            "Lead solder is too strong for copper",
            "Lead solder only works on DWV plastic",
            "Lead-free solder is required only for gas piping",
        ],
    ),
    q(
        "medium",
        "A PEX crimp or expansion joint should be made with:",
        "Use the tool and fittings listed for that PEX system. Mixing crimp rings, expansion rings, and brands incorrectly is a leak and listing failure.",
        "The manufacturer’s compatible fittings and the matching listed tool",
        [
            "Any hose clamp from the hardware aisle",
            "Electrical tape as the primary seal",
            "A soldered copper coupling on the PEX without a transition fitting",
        ],
    ),
    q(
        "medium",
        "Why should a water heater’s T&P relief valve never be plugged or capped?",
        "The T&P valve is a safety device that relieves excessive temperature or pressure. Capping it can cause tank rupture.",
        "It is a safety device; blocking it can allow the tank to overpressure",
        [
            "The valve is only decorative",
            "Capping it improves energy efficiency",
            "The drain pan already provides overpressure protection",
        ],
    ),
    q(
        "medium",
        "When working with cast-iron DWV, which hazard is commonly overlooked?",
        "Cast iron is heavy and can shatter. Support the pipe, use proper cutters, and protect eyes. Letting an unsupported stack drop is dangerous.",
        "Unsupported sections are heavy and can crush or shatter when cut",
        [
            "Cast iron is as light as PVC of the same size",
            "Cast iron dust is a refreshment if inhaled",
            "Cast iron never needs support after a cut",
        ],
    ),
    q(
        "medium",
        "A job requires soldering and a combustible-gas detector. Why test the area before lighting a torch?",
        "A leak from another trade’s work or an existing gas line can create an explosive atmosphere. Test, ventilate, and isolate fuel gas before using an open flame.",
        "An undetected fuel-gas leak can ignite when the torch is lit",
        [
            "Torches cannot ignite fuel gas by design",
            "Gas detectors are only for refrigerant work",
            "Soldering flux will neutralize any gas leak",
        ],
    ),
    q(
        "medium",
        "Which statement about silica dust from cutting concrete or masonry for plumbing sleeves is correct?",
        "Crystalline silica is a serious inhalation hazard. Use wet methods or local exhaust and required respiratory protection—not dry cutting in a closed room without controls.",
        "Control the dust with wet methods or exhaust and appropriate respiratory protection",
        [
            "Silica dust is only a cleanup nuisance and is not a health concern",
            "Dry cutting indoors without controls is the preferred method",
            "A paper shop towel over the nose is full protection",
        ],
    ),
    q(
        "medium",
        "Why should electrical bonding/grounding connections on metal water piping be treated carefully during repairs?",
        "Metal water piping may be part of the electrical grounding/bonding path. Opening it can energize piping or lose a ground. Coordinate isolation and restore listed bonding as required.",
        "The piping may be part of the electrical grounding or bonding path",
        [
            "Water pipes never carry electrical current under any fault",
            "Removing a bonding jumper always improves water quality",
            "Dielectric unions eliminate all electrical safety concerns permanently without bonding",
        ],
    ),
    q(
        "hard",
        "A technician must replace a section of water service that also has an electrical grounding electrode conductor attached. What is the safest approach?",
        "Do not disconnect a grounding electrode path without an electrically safe plan. Coordinate so the electrical grounding/bonding remains intact or is properly transferred, and isolate water before cutting.",
        "Plan the repair so water is isolated and the electrical grounding/bonding path is not left open",
        [
            "Cut the grounding conductor first and leave it disconnected",
            "Assume the water pipe is never an electrical path in any building",
            "Hold both pipe ends by hand to keep continuity while cutting",
        ],
    ),
    q(
        "hard",
        "Hot work is required in a mechanical room with a gas-fired water heater. What is an appropriate precaution sequence?",
        "Check for gas leaks, isolate and verify as needed, ventilate, protect combustibles, and have fire control ready. Lighting a torch beside an odor of gas is unsafe.",
        "Check the atmosphere for fuel gas, control ignition sources, and protect combustibles",
        [
            "Light the torch immediately to burn off any gas",
            "Disable the T&P valve so it cannot drip on the torch",
            "Close the mechanical-room door to keep oxygen in",
        ],
    ),
    q(
        "hard",
        "A sewer combination machine will be used on a line that may contain chemical drain cleaner. What should the technician do?",
        "Unknown chemicals plus mechanical agitation can splash caustic product. Identify what was used if possible, use chemical-resistant PPE, flush if appropriate, and do not mix additional chemicals.",
        "Treat the line as chemically contaminated: PPE, avoid mixing products, and control splash",
        [
            "Add a second chemical cleaner to neutralize by guesswork",
            "Run the cable with no eye protection because the water will dilute anything",
            "Heat the pipe with a torch to drive off chemicals",
        ],
    ),
    q(
        "hard",
        "After heavy rain, a previously protected sewer trench has sloughed at the edges and spoil has crept closer to the wall. What should happen before anyone re-enters?",
        "Rain and sloughing change the excavation. Re-inspect, restore cave-in protection, keep spoil set back from the edge, and confirm a safe means of egress. A trench that was acceptable yesterday is not automatically safe after weather or soil movement.",
        "Re-inspect, restore cave-in protection and spoil setback, and confirm safe egress",
        [
            "Re-enter immediately because the trench was protected before the rain",
            "Use the pipe itself as a shield by lying under it",
            "Park the truck on the spoil pile to compact the soil",
        ],
    ),
    q(
        "hard",
        "Press-connect copper fittings are being used near a previously soldered joint. Why must the manufacturer’s temperature and distance limits be respected?",
        "Excess heat can damage O-rings or sealing elements in press fittings. Follow listed clearances and cooling methods rather than soldering immediately against a press fitting.",
        "Heat from soldering can damage the press fitting’s sealing element",
        [
            "Press fittings are designed to be annealed with a torch after crimping",
            "Solder flux improves press-fitting O-rings",
            "Temperature limits only apply to plastic pipe, never copper press",
        ],
    ),
]

WATER = [
    q(
        "easy",
        "What is the purpose of a shutoff valve on a water-supply branch?",
        "A shutoff lets a fixture or branch be isolated for repair without shutting down the entire building.",
        "To isolate a fixture or branch for service",
        [
            "To increase water pressure in that branch",
            "To vent the DWV system",
            "To mix hot and cold to a safe temperature automatically",
        ],
    ),
    q(
        "easy",
        "Why are potable water systems kept separate from sewage and nonpotable sources?",
        "Cross-connections can contaminate drinking water. Backflow prevention and physical separation protect the potable supply.",
        "To prevent contamination of drinking water",
        [
            "To make pipes easier to paint",
            "Because sewage pipes cannot be larger than water pipes",
            "To raise the water heater’s energy factor",
        ],
    ),
    q(
        "easy",
        "What does a pressure-reducing valve (PRV) typically do on a building water service?",
        "A PRV lowers high street pressure to a safer building pressure that protects fixtures, valves, and piping.",
        "Reduce incoming water pressure to a lower building pressure",
        [
            "Increase street pressure for better shower flow",
            "Heat the incoming water",
            "Add chlorine to the water",
        ],
    ),
    q(
        "easy",
        "Hot and cold water supplies to a lavatory are typically connected so that:",
        "By convention, hot is on the left and cold on the right for the user. Reversing them is a scald and usability issue.",
        "Hot is on the left and cold is on the right as used by the occupant",
        [
            "Hot and cold are interchangeable with no user impact",
            "Both supplies must be hot to meet code",
            "Cold water must pass through the water heater first",
        ],
    ),
    q(
        "easy",
        "What is water hammer?",
        "Water hammer is a pressure surge from a sudden stop of flow, often heard as banging. Arrestors or other control methods reduce the surge.",
        "A pressure surge when flowing water is stopped suddenly",
        [
            "A type of pipe thread",
            "A vent fitting used on a stack",
            "A chemical used to solder copper",
        ],
    ),
    q(
        "easy",
        "Why is dielectric isolation often used when joining copper and galvanized steel water piping?",
        "Dissimilar metals in water can corrode galvanically. A listed dielectric union or isolating fitting reduces that corrosion.",
        "To reduce galvanic corrosion between dissimilar metals",
        [
            "To increase electrical current through the pipe",
            "To make the joint easier to solder",
            "To raise water pressure",
        ],
    ),
    q(
        "easy",
        "What is the function of an expansion tank on a closed, heated potable-water system?",
        "When water is heated it expands. In a closed system the expansion tank provides space for that expansion so pressure does not rise excessively.",
        "Absorb expanded water volume so system pressure does not rise excessively",
        [
            "Store extra sewage",
            "Increase incoming street pressure",
            "Replace the T&P relief valve",
        ],
    ),
    q(
        "medium",
        "A hose bibb without backflow protection is a concern because:",
        "A hose submerged in a dirty bucket or pool can siphon contaminants into the potable system when pressure drops. Use a listed vacuum breaker or other backflow device.",
        "A submerged hose can siphon contaminants into the potable water",
        [
            "Hose bibbs cannot freeze",
            "Backflow devices reduce pipe diameter only for appearance",
            "Hoses always flow in one direction regardless of pressure",
        ],
    ),
    q(
        "medium",
        "What is a practical difference between an atmospheric vacuum breaker and a reduced-pressure-zone (RPZ) backflow preventer?",
        "An atmospheric vacuum breaker is for back-siphonage only under limited conditions and must not be under continuous pressure or subject to backpressure. An RPZ can protect against both back-siphonage and backpressure on higher-hazard connections. Choose by hazard and listing, not by price.",
        "A vacuum breaker is for back-siphonage only; an RPZ also protects against backpressure on higher-hazard uses",
        [
            "They are identical devices with different paint colors",
            "An RPZ is only for DWV, never potable water",
            "A vacuum breaker is designed to replace a water heater T&P valve",
        ],
    ),
    q(
        "medium",
        "Why might a recirculation line be installed on a domestic hot-water system?",
        "Recirc keeps hot water near fixtures to reduce wait time and wasted water. It must be balanced and controlled so it does not overheat piping or waste energy continuously without need.",
        "To deliver hot water to distant fixtures with less wait and waste",
        [
            "To mix sewage with hot water for faster draining",
            "To replace the building’s cold-water service",
            "To reduce water-heater temperature below a safe storage range as the only goal",
        ],
    ),
    q(
        "medium",
        "A water-service pipe is being installed below a slab. Why does material listing and protection matter?",
        "Buried potable pipe must be listed for the location, protected from damage, and installed to prevent contamination. Random indoor tubing may not be rated for burial.",
        "The pipe must be listed for burial and protected from damage and contamination",
        [
            "Any indoor drain pipe can be used as a water service",
            "Burial depth never matters if the pipe is copper-colored",
            "Water service pipe should be perforated like a French drain",
        ],
    ),
    q(
        "medium",
        "What is a common reason to install a water hammer arrestor at a quick-closing valve, such as a washing machine box?",
        "Quick-closing valves stop flow suddenly. An arrestor absorbs the surge that would otherwise bang and stress piping.",
        "To absorb the pressure surge from sudden valve closure",
        [
            "To heat the cold water",
            "To vent sewer gas",
            "To reduce pipe diameter",
        ],
    ),
    q(
        "medium",
        "Why should a water heater’s cold inlet often include a dip tube (or equivalent design)?",
        "The dip tube sends incoming cold water to the bottom so hot water is drawn from the top. A failed dip tube can cause lukewarm water at fixtures.",
        "To deliver incoming cold water to the bottom of the tank",
        [
            "To prevent the T&P valve from ever opening",
            "To mix flue gases into the potable water",
            "To increase anode rod consumption on purpose",
        ],
    ),
    q(
        "medium",
        "An anode rod in a steel water heater is intended to:",
        "The anode is sacrificial protection for the tank steel. Inspect/replace per condition; it is not a mixing valve.",
        "Corrode preferentially so the tank steel lasts longer",
        [
            "Set the exact outlet temperature",
            "Increase incoming pressure",
            "Replace the need for a T&P valve",
        ],
    ),
    q(
        "medium",
        "Why is excessive water velocity in a potable-water pipe a concern?",
        "High velocity causes noise, erosion of fittings, and greater water-hammer surge when valves close. Size piping for required fixture flow without treating a potable system like a hydronic loop that is “balanced” with circuit setters. Distant fixtures still need adequate pressure and flow.",
        "It can cause noise, erosion, and more severe water hammer",
        [
            "Higher velocity always improves water quality",
            "Velocity only matters on DWV stacks, never on water pipe",
            "Codes require the highest possible velocity so pipes can be smaller without limit",
        ],
    ),
    q(
        "medium",
        "Why is a listed thermal expansion control method needed when a check valve or PRV creates a closed system?",
        "Heated water in a closed system has nowhere to go, so pressure rises and can drip T&P valves or damage tanks. An expansion tank or listed equivalent is the usual control.",
        "Heating water in a closed system raises pressure that must be absorbed",
        [
            "Closed systems cannot be heated, so expansion control is decorative",
            "T&P valves are intended to operate on every heater cycle as the expansion method",
            "Expansion tanks are only for hydronic heating, never potable water",
        ],
    ),
    q(
        "medium",
        "A water heater’s T&P discharge was capped because the valve dripped during heat-up on a closed system. What is the correct action?",
        "A T&P valve must never be capped or blocked. Restore an unobstructed discharge immediately. If the tank is overpressured or the valve cannot relieve, shut the heater down and verify that a listed relief path works before returning it to service. Then correct thermal expansion (expansion tank or listed equivalent) so the T&P is not used as a cycling expansion device. Dripping during heat-up is a clue, not a reason to disable the safety.",
        "Restore the unobstructed T&P path immediately; shut down and verify relief if overpressure exists, then correct expansion",
        [
            "Leave the cap on and install a larger dip tube later",
            "Raise the thermostat so the valve seats more firmly against the cap",
            "Replace the anode rod only, because dripping T&P valves are always a tank-corrosion issue",
        ],
    ),
    q(
        "medium",
        "What is the usual purpose of a thermostatic mixing valve at a water heater or fixture group?",
        "It blends hot and cold to a safer delivered temperature to reduce scald risk while allowing the tank to store water hot enough to limit bacterial growth, per design. It is not a backflow preventer.",
        "Limit delivered hot-water temperature to reduce scald risk",
        [
            "Increase street pressure",
            "Replace the building sewer vent",
            "Add disinfectant to the cold-water service",
        ],
    ),
    q(
        "medium",
        "PEX, copper, and CPVC can all be used for potable water when:",
        "Each material must be listed for potable water and installed with compatible fittings, support, temperature/pressure ratings, and protection from UV, freeze, and damage.",
        "They are listed for the use and installed with compatible fittings and support",
        [
            "They are mixed in any combination without transition fittings",
            "They are used only for DWV, never potable water",
            "They are glued with PVC drain cement regardless of material",
        ],
    ),
    q(
        "hard",
        "A building has low flow at upper-floor fixtures only when several lower fixtures run. Street pressure is adequate at the water meter. What is a logical early investigation?",
        "The pattern suggests distribution friction, undersized piping, a failing PRV, a partially closed valve, or a clogged strainer—not automatically a bad faucet washer on every upper fixture. Measure pressures at rest and under load at several points.",
        "Measure pressure at rest and under load at the meter, PRV, and upper floors",
        [
            "Replace every upper-floor faucet cartridge as the first step",
            "Remove the building PRV permanently to raise pressure without evaluation",
            "Cap the main vent stack to increase water pressure",
        ],
    ),
    q(
        "hard",
        "A reduced-pressure-zone backflow preventer is discharging from the relief port. What is the appropriate response?",
        "Relief discharge can mean a fouled check, backpressure, or a failing device. It is protecting the potable system; do not cap the relief. Diagnose and repair/replace the assembly per listing and testing requirements.",
        "Do not cap the relief; diagnose whether the assembly is fouled or seeing backpressure",
        [
            "Cap the relief port so water is not wasted",
            "The discharge always means the device should be removed permanently",
            "Connect the relief port to the potable cold-water line to recycle the water",
        ],
    ),
    q(
        "hard",
        "Hot-water delay is excessive at a distant fixture, but nearby fixtures are prompt. The water heater recovers normally. What should be evaluated?",
        "The heater is producing hot water; the issue is distribution—pipe length, missing recirc/return, failed recirc pump/check, or a crossover. Do not raise tank temperature to an unsafe level as the first fix.",
        "Distribution path, recirc operation, and possible hot/cold crossover",
        [
            "Raise the tank to the maximum thermostat stop without investigating distribution",
            "Replace the building sewer because delay is a DWV symptom",
            "Remove the mixing valve and leave untempered water as the only solution without evaluating scald risk",
        ],
    ),
    q(
        "hard",
        "A copper water system has pinhole leaks in a localized area. Chloride/aggressive water is suspected. What is a sound next step beyond patching one hole?",
        "Repeated pinholes can be corrosion, electrical stray current, or installation damage. Patching one hole without investigating water chemistry, grounding/bonding, and remaining pipe condition is incomplete.",
        "Investigate water chemistry, grounding/bonding, and the condition of remaining pipe",
        [
            "Keep soldering over holes indefinitely without investigation",
            "Add a dielectric union on a same-metal copper-to-copper joint as the only fix",
            "Increase system pressure to keep pinholes in compression",
        ],
    ),
    q(
        "hard",
        "A booster pump is being added for upper floors. What control issue must be addressed?",
        "A booster can create excessive pressure, dead-head, or backfeed. It needs proper pressure controls, check valves, and isolation, and must not overpressurize fixtures or the heater.",
        "Pressure control, check/isolation valves, and protection against overpressurizing the building",
        [
            "Running the pump continuously at full speed with no pressure control",
            "Connecting the pump discharge to the sewer to relieve extra pressure",
            "Removing all shutoff valves so the pump cannot be isolated",
        ],
    ),
]

DWV = [
    q(
        "easy",
        "What is the primary purpose of a fixture trap?",
        "A trap holds a water seal that blocks sewer gas from entering the building through the fixture.",
        "To hold a water seal that blocks sewer gas",
        [
            "To increase water-supply pressure",
            "To grind solids into the water heater",
            "To replace the need for a vent in every case",
        ],
    ),
    q(
        "easy",
        "Why are DWV systems vented?",
        "Vents admit air so waste can flow without siphoning trap seals, and they relieve positive pressure that can blow traps. Both siphonage and blowback protection matter. Vents are not potable-water air vents.",
        "To protect trap seals from siphonage and positive pressure, and to let waste flow",
        [
            "To pressurize sewage for faster flow always",
            "To add oxygen to potable water",
            "To heat the waste stack",
        ],
    ),
    q(
        "easy",
        "What is a cleanout for?",
        "A cleanout provides access to clear blockages in DWV piping without cutting the pipe.",
        "To provide access for clearing blockages",
        [
            "To add makeup water to the water heater",
            "To connect a hose bibb to the sewer",
            "To increase trap seal depth without limit",
        ],
    ),
    q(
        "easy",
        "Horizontal DWV piping is installed with slope so that:",
        "Gravity slope lets liquids carry solids to the stack or sewer. Insufficient slope lets solids settle and cause stoppages. Follow the required minimum slope for the pipe size. The old claim that a steeper building drain makes liquids “outrun” solids is not a sound basis for flattening a drain.",
        "Waste can flow by gravity and carry solids",
        [
            "The pipe can hold water like a supply line",
            "Sewer gas is forced into fixtures",
            "Traps are siphoned on every flush as a design goal",
        ],
    ),
    q(
        "easy",
        "A toilet (water closet) typically connects to the drain with a:",
        "A closet flange and wax or listed seal connect the toilet to the drain. A trap is integral to the fixture.",
        "Closet flange and a listed seal (such as a wax ring)",
        [
            "Garden-hose thread only",
            "Soldered copper stub-out into the bowl",
            "Direct connection to the water heater T&P drain",
        ],
    ),
    q(
        "easy",
        "What is the difference between a soil stack and a waste stack?",
        "A soil stack receives discharge from water closets (and often other fixtures). A waste stack receives waste from fixtures other than water closets. Both are vertical DWV pipes; the distinction is whether soil (water-closet) waste is included.",
        "A soil stack carries water-closet discharge; a waste stack does not",
        [
            "They are interchangeable names for the cold-water riser",
            "A waste stack is only the gas vent from a water heater",
            "A soil stack is electrical conduit in a wet wall",
        ],
    ),
    q(
        "easy",
        "Why should a trap not be double-trapped without a designed exception?",
        "Two traps in series can cause air lock and poor drainage. Each fixture typically has one trap, properly vented.",
        "Two traps in series can air-lock and drain poorly",
        [
            "Double trapping always increases vent capacity",
            "Double traps are required on every lavatory",
            "A second trap raises water-supply pressure",
        ],
    ),
    q(
        "medium",
        "A lavatory gurgles and the trap seal is lost when a nearby toilet is flushed. What is a likely DWV issue?",
        "The symptom is classic siphonage or pressure fluctuation from inadequate venting. It is not a water-heater problem.",
        "Inadequate venting allowing the trap to be siphoned or disturbed",
        [
            "A failed water-heater anode",
            "A closed building PRV",
            "Reversed hot and cold supplies only",
        ],
    ),
    q(
        "medium",
        "What is a wet vent, in general terms?",
        "A wet vent is a pipe that vents one fixture while also serving as a drain for another, under specific size and configuration rules. It is not a potable recirc line.",
        "A drain pipe that is also used to vent another fixture under allowed configurations",
        [
            "A water-supply pipe that is intentionally filled with air",
            "A vent that must remain completely dry in all designs",
            "A storm leader used as a potable-water riser",
        ],
    ),
    q(
        "medium",
        "Why are fixture-unit values used in DWV sizing?",
        "Fixture units estimate probable discharge load so pipes and vents can be sized. They are not a measure of water quality.",
        "To estimate probable load for sizing drains and vents",
        [
            "To measure lead content in solder",
            "To set water-heater thermostat calibration",
            "To calculate trench cave-in protection",
        ],
    ),
    q(
        "medium",
        "A building drain that is almost flat has repeated stoppages. What is a likely contributing factor?",
        "Insufficient slope lets solids settle. Repair may require correcting grade, not just repeated snaking as the only long-term fix.",
        "Insufficient slope allowing solids to settle",
        [
            "Too much vent capacity as the only cause",
            "A water hammer arrestor on the drain",
            "A mixing valve on the water heater",
        ],
    ),
    q(
        "medium",
        "What is the purpose of a trap primer where one is used?",
        "A trap primer replenishes trap seals that can dry out on rarely used drains, which would otherwise pass sewer gas.",
        "To maintain the trap water seal on infrequently used drains",
        [
            "To increase potable water pressure",
            "To grind food waste",
            "To replace the main building vent",
        ],
    ),
    q(
        "medium",
        "An air-admittance valve (AAV), where permitted, is intended to:",
        "An AAV admits air to protect traps when the system goes negative, but it does not relieve positive pressure like an open vent terminal. Use only where the applicable code and listing allow.",
        "Admit air to protect a trap seal where that method is allowed",
        [
            "Replace every open vent terminal on a high-rise as a universal rule",
            "Discharge sewage to the roof",
            "Connect the water heater flue to the DWV system",
        ],
    ),
    q(
        "medium",
        "Why should a dishwasher typically discharge through an air gap or a high loop as required by the installation?",
        "An air gap or required high loop helps prevent wastewater from siphoning back into the dishwasher and contaminating it.",
        "To reduce the chance of wastewater siphoning back into the appliance",
        [
            "To increase wash temperature above the heating element rating",
            "To vent the water heater",
            "To reduce trap seal depth",
        ],
    ),
    q(
        "medium",
        "A kitchen sink has a garbage disposer. What DWV connection practice is important?",
        "The disposer and sink must drain through a properly sized, trapped, and vented path. Connecting a disposer into a dirty-arm in a way that traps another fixture incorrectly causes backups and leaks.",
        "The discharge must be trapped and vented as a legal fixture connection, not tied in a way that double-traps another fixture",
        [
            "The disposer should discharge into the water-supply riser",
            "The disposer can replace the trap seal entirely",
            "The disposer drain should be smaller than the trap always, even if undersized for the load",
        ],
    ),
    q(
        "medium",
        "What is a common reason to install a backwater valve on a building drain?",
        "A backwater valve can protect fixtures below the next upstream manhole cover (or as required) from sewer surcharge. It must be accessible for maintenance.",
        "To reduce the risk of public-sewer surcharge flooding back into the building",
        [
            "To increase potable water pressure",
            "To replace fixture traps",
            "To mix storm and sanitary without restriction",
        ],
    ),
    q(
        "medium",
        "Offsetting a soil stack requires attention because offsets can:",
        "Offsets can create additional load, need extra fittings, and can affect venting and flow. They must follow the applicable sizing and fitting rules—not be made with supply elbows.",
        "Affect flow and venting and must use appropriate fittings and sizing",
        [
            "Always increase water-supply pressure",
            "Be made with shutoff valves like a water riser",
            "Replace the need for a cleanout",
        ],
    ),
    q(
        "medium",
        "Why is a vertical stack typically larger than some of the horizontal branches that feed it?",
        "The stack can receive combined load from multiple branches. Sizing follows fixture units and code tables, not matching the smallest branch for convenience.",
        "It may carry the combined load of multiple fixtures and branches",
        [
            "Vertical pipes must always be smaller than branches",
            "Stack size is chosen only to match tile holes, not load",
            "Stacks carry pressurized potable water",
        ],
    ),
    q(
        "medium",
        "A floor drain in a mechanical room keeps losing its trap seal. What are logical causes to consider?",
        "Evaporation, siphonage from poor venting, or a leaky primer line can lose the seal. Pouring water is a temporary check; the cause still needs correction.",
        "Evaporation, siphonage, or a failed trap primer",
        [
            "A water-heater anode only",
            "A closed hose-bibb vacuum breaker only",
            "Reversed lavatory supplies only",
        ],
    ),
    q(
        "hard",
        "A new horizontal branch was tied into a horizontal drain with a sanitary tee laid on its back. The fixture drains slowly and nearby traps gurgle. What should be suspected?",
        "A sanitary tee is for vertical drainage into a stack, with the branch entering the upright body. Laid on its back in a horizontal run it creates a poor flow pattern, turbulence, and siphonage. A wye or combination wye-and-eighth bend is the usual horizontal combination. Investigate fitting geometry before blaming the water heater.",
        "A sanitary tee used on its back instead of a combination fitting in the horizontal run",
        [
            "A failed expansion tank as the first DWV cause",
            "A mixing valve set too low",
            "A PRV set too high",
        ],
    ),
    q(
        "hard",
        "After a heavy rain, lower-level fixtures overflow with sewage even though they were not used. What is a logical system-level concern?",
        "This pattern suggests sewer surcharge, a blocked building sewer, or a combined-sewer issue—not a dripping faucet. Check the building sewer, backwater protection, and whether storm water is illegally tied in.",
        "Public or building sewer surcharge, blockage, or improper storm connections",
        [
            "A dripping lavatory faucet as the only cause",
            "A water hammer arrestor on the washer box",
            "A new water-heater anode",
        ],
    ),
    q(
        "hard",
        "A long, undervented horizontal branch serves several lavatories. Traps are being pulled. What is the most appropriate correction path?",
        "Protect trap seals with proper venting (or an allowed alternative) and correct pipe size/length. Installing AAVs or reventing must follow what the applicable code allows. Do not reduce trap size below listing to “speed flow.”",
        "Provide code-allowed venting and correct the branch sizing/layout",
        [
            "Remove all traps so air can flow freely",
            "Cap the roof vent to keep sewer gas in the pipe",
            "Connect the branch to the water-service pipe for extra flow",
        ],
    ),
    q(
        "hard",
        "A combination waste-and-vent system, where allowed, depends on:",
        "Combination waste-and-vent designs are tightly limited: fixture types, pipe size, slope, and cleanouts. They are not a universal substitute for conventional venting on every fixture.",
        "Specific allowed fixtures, oversizing, and layout limits—not a universal vent substitute",
        [
            "Using it on water closets and kitchen sinks in every jurisdiction without restriction",
            "Eliminating all cleanouts",
            "Running it at a steep slope to replace pipe diameter",
        ],
    ),
    q(
        "hard",
        "Smoke or peppermint testing a DWV system is used primarily to:",
        "These tests help find leaks and dry traps that would admit sewer gas. They are not potable-water disinfection methods.",
        "Locate leaks or failed trap seals that can admit sewer gas",
        [
            "Increase water-heater efficiency",
            "Calibrate a PRV",
            "Remove hard-water scale from copper",
        ],
    ),
]

FIXTURES = [
    q(
        "easy",
        "Why is a toilet supply stop installed below the tank?",
        "The stop isolates the toilet for repair without shutting down the building water.",
        "To isolate the toilet for repair",
        [
            "To vent the soil stack",
            "To grind solids",
            "To mix drain cleaner into the supply",
        ],
    ),
    q(
        "easy",
        "What is the usual purpose of an aerator on a lavatory faucet?",
        "An aerator mixes air into the stream, controls splash, and often limits flow. It is a common clog point for debris.",
        "To shape the stream, reduce splash, and often limit flow",
        [
            "To increase trap seal depth",
            "To heat the water electrically",
            "To prevent the need for a shutoff valve",
        ],
    ),
    q(
        "easy",
        "A shower valve that is not scald-protected can be dangerous because:",
        "A sudden drop in cold-water pressure can send water to unsafe temperatures. Pressure-balancing or thermostatic valves reduce that risk.",
        "A loss of cold water can send scalding water to the outlet",
        [
            "Shower valves cannot exceed room temperature",
            "Scald protection is only for outdoor hose bibbs",
            "Hot water is always limited by the aerator",
        ],
    ),
    q(
        "easy",
        "Why should a water heater have a drain pan where leakage could damage the structure?",
        "Tanks leak. A pan with a drain outlet can limit water damage. It does not replace the T&P valve.",
        "To catch leakage and route it away from finished structure",
        [
            "To store extra potable water for drinking",
            "To replace the T&P relief valve",
            "To increase recovery rate",
        ],
    ),
    q(
        "easy",
        "A listed flexible water-heater connector is used because:",
        "It provides a practical, listed transition and some vibration isolation. It must be the correct material for potable water and not a random washing-machine hose if not listed for that use.",
        "It is a listed way to connect the heater to the piping with some flexibility",
        [
            "Any garden hose is an acceptable permanent connector",
            "Flexible connectors replace dielectric isolation in all cases",
            "They eliminate the need for shutoff valves",
        ],
    ),
    q(
        "easy",
        "What is a fixture rough-in?",
        "Rough-in is the installation of piping and supports to the correct locations and heights before fixtures are set.",
        "Installing piping to the correct locations before setting fixtures",
        [
            "Painting the fixtures",
            "The final disinfection of the water service only",
            "Setting the water-heater thermostat",
        ],
    ),
    q(
        "easy",
        "A frost-proof wall hydrant should be installed so that:",
        "The valve seat is in the heated space and the hydrant pitches down to drain after the handle is shut, so standing water does not freeze in the wall. It is not a DWV cleanout and does not replace backflow protection on the hose thread.",
        "The seat is in the heated space and the hydrant pitches down to drain",
        [
            "The valve seat is in the cold exterior wall with no drain pitch",
            "The hydrant is used as a DWV cleanout",
            "The hose thread is permanently capped so it cannot freeze",
        ],
    ),
    q(
        "medium",
        "A pressure-balancing shower valve is primarily intended to:",
        "It compensates for pressure changes between hot and cold so outlet temperature stays more stable. It is not a trap primer.",
        "Reduce temperature swing when supply pressures change",
        [
            "Increase flow without limit",
            "Replace the water heater",
            "Vent the shower drain",
        ],
    ),
    q(
        "medium",
        "When setting a toilet, a common leak path is:",
        "The closet-flange seal (wax or listed alternative) and closet bolts/flange height are frequent leak sources. Do not over-tighten the tank bolts to the point of cracking porcelain.",
        "The closet-flange seal or an improperly set flange height",
        [
            "The roof vent cap only",
            "The water-heater anode",
            "The building PRV screen only",
        ],
    ),
    q(
        "medium",
        "A kitchen faucet with a pull-down sprayer needs backflow protection because:",
        "The sprayer can be left in a dirty sink. Without protection, contaminated water could be siphoned into the supply.",
        "The sprayer can be submerged in a contaminated sink",
        [
            "Kitchen faucets never connect to potable water",
            "Sprayers increase DWV slope",
            "Backflow protection heats the water",
        ],
    ),
    q(
        "medium",
        "How should a food-waste disposer be electrically connected?",
        "A disposer is a grounded appliance in a wet location. Install it per its listing: equipment grounding conductor, strain relief, and a local disconnect or switch. Cord-and-plug or hardwired methods are both acceptable only when the listing allows them. Do not “isolate” the appliance from ground, and do not use the drain hose as a grounding path.",
        "Per its listing, with an equipment grounding conductor and a local disconnect or switch",
        [
            "Electrically isolated from ground so it cannot shock anyone",
            "Grounded through the dishwasher drain hose only",
            "Fed by any household extension cord as a permanent connection",
        ],
    ),
    q(
        "medium",
        "Accessible fixture connections matter because:",
        "Stops, traps, and supply risers need service access. Concealing a trap with no access panel makes future repair destructive.",
        "Stops, traps, and risers will need future service",
        [
            "Access is only for appearance during inspection photos",
            "Concealed unaccessible traps never clog",
            "Codes prohibit all access panels",
        ],
    ),
    q(
        "medium",
        "A bidet or similar fixture with submerged inlets requires backflow protection because:",
        "Submerged inlets are a direct cross-connection risk. Use the listed vacuum breaker or air gap the manufacturer specifies.",
        "Contaminated fixture water could enter the potable supply",
        [
            "These fixtures do not use potable water",
            "Backflow protection is only for outdoor hose bibbs",
            "A trap primer prevents all backflow",
        ],
    ),
    q(
        "medium",
        "When hanging a wall-hung lavatory, the carrier or blocking must:",
        "The fixture load transfers to the structure. Drywall anchors alone are not a substitute for proper blocking or a carrier.",
        "Transfer the fixture load to the building structure",
        [
            "Hang from the trap arm only",
            "Be supported by the supply stops",
            "Use only adhesive on drywall with no blocking",
        ],
    ),
    q(
        "medium",
        "A washing-machine standpipe must be tall enough and trapped/vented because:",
        "The standpipe receives a pumped discharge. Too short and it overflows; missing trap/vent creates sewer-gas and drainage problems.",
        "It must accept the pumped discharge without overflowing and must be trapped and vented",
        [
            "Standpipes are connected to the water heater flue",
            "Standpipes replace the need for a water-supply stop",
            "Standpipes should discharge onto the floor as a design",
        ],
    ),
    q(
        "medium",
        "Why is an ice-maker supply often required to have a saddle-valve-free, listed shutoff and appropriate tubing?",
        "Old saddle valves leak and fail. Use a listed shutoff and tubing rated for potable water, with protection against kinks and freeze.",
        "Saddle valves are failure-prone; use a listed shutoff and rated tubing",
        [
            "Any automotive fuel hose is acceptable",
            "Ice makers should be teed into the DWV stack",
            "Ice-maker lines must be left unvalved",
        ],
    ),
    q(
        "medium",
        "A water-heater T&P discharge pipe should be installed so that:",
        "Discharge must be routed to a safe location, full-size, without a thread cap, and without traps that can block the valve. Exact termination rules vary; the principle is unobstructed, visible, safe discharge.",
        "Relief water can leave unobstructed to a safe, visible location",
        [
            "The pipe is capped so the valve cannot drip",
            "The pipe is smaller than the valve outlet to increase velocity",
            "The pipe is trapped like a fixture to hold a seal",
        ],
    ),
    q(
        "medium",
        "Offset closet flanges are used when:",
        "The drain is not centered on the finished wall location. They are not a fix for an undersized drain or a missing vent.",
        "The rough-in location does not align with the finished toilet location",
        [
            "The vent stack is too large",
            "The water heater recovery is low",
            "The PRV is set too high",
        ],
    ),
    q(
        "medium",
        "A fixture trap arm that is too long for its vent location can:",
        "An overly long trap arm can siphon the trap. Length limits exist for a reason; do not extend with extra pipe as a convenience.",
        "Lose its trap seal to siphonage",
        [
            "Increase potable water pressure",
            "Replace the need for a cleanout",
            "Convert the drain to a supply line",
        ],
    ),
    q(
        "hard",
        "A newly set toilet rocks and seeps at the base. The flange is below the finished floor. What is the appropriate correction?",
        "The flange should be at the proper height relative to the finished floor, with a listed seal. Stacking extra wax as the only fix on a low, broken, or poorly supported flange is unreliable. Repair the flange height/support.",
        "Repair flange height and support so the seal is compressed evenly",
        [
            "Keep adding wax rings indefinitely without repairing the flange",
            "Over-tighten closet bolts until the porcelain cracks to stop the rock",
            "Caulk the entire base with no path to notice a future leak, without fixing the flange",
        ],
    ),
    q(
        "hard",
        "A thermostatic mixing valve hunts and the shower temperature swings. Supply pressures are stable. What should be inspected next?",
        "Thermostatic valves need minimum flow, correct cartridge orientation, inlet screens, and sometimes check stops. Hunting can be debris or a failed cartridge—not a DWV vent issue.",
        "Inlet screens, check stops, cartridge condition, and minimum flow",
        [
            "The main building sewer vent only",
            "The water-heater anode color only",
            "The lavatory trap arm slope only",
        ],
    ),
    q(
        "hard",
        "A commercial fixture battery is being roughed with a carrier system. Why must carrier ratings and alignment be followed?",
        "Carriers support the fixture load and align the waste connection. An undersized or misaligned carrier leaks and can pull fixtures off the wall.",
        "The carrier supports the fixture and must align with the waste outlet",
        [
            "Carriers are only decorative escutcheons",
            "Alignment does not matter if extra wax is used on a wall-hung water closet",
            "Carriers replace the need for fixture traps",
        ],
    ),
    q(
        "hard",
        "An electric water heater shows scorch marks at a terminal and the element does not heat. What is the safest early step?",
        "Treat it as an electrical failure: isolate power, verify de-energized, inspect terminations and element resistance. Do not work the electrical section wet, and do not raise the thermostat with damaged wiring.",
        "Isolate power, verify it is de-energized, then inspect terminations and the element",
        [
            "Tighten the terminal while the heater is energized",
            "Bypass the high-limit (ECO) permanently so it will heat",
            "Fill the T&P discharge with a cap so drips cannot reach the wiring",
        ],
    ),
    q(
        "hard",
        "A kitchen island sink cannot take a conventional vent through a cabinet to the ceiling. What should the designer/technician do?",
        "Use an allowed island-vent configuration (loop vent or other permitted method) per the applicable code. Do not omit the trap or tie the drain to a supply line. AAVs are only a solution where specifically permitted.",
        "Use a code-allowed island-vent or other permitted method for that fixture",
        [
            "Omit the trap because island sinks do not produce sewer gas",
            "Pump the sink into the water heater drain pan",
            "Run an untrapped pipe into a nearby floor drain as the only method without checking code",
        ],
    ),
]

SERVICE = [
    q(
        "easy",
        "A fixture has no water. Nearby fixtures work. What should be checked first?",
        "The local stop may be closed, the supply riser kinked, or the faucet cartridge clogged. Do not shut down and drain the whole building first.",
        "The fixture shutoff, supply risers, and the faucet/cartridge inlet screens",
        [
            "The municipal treatment plant chlorine level",
            "The building sewer slope across town",
            "The water-heater anode immediately",
        ],
    ),
    q(
        "easy",
        "A toilet runs continuously. What is a common cause to inspect first?",
        "A leaking flapper, misadjusted fill valve, or tank water level above the overflow are common. This is not a sewer-main problem by itself.",
        "Flapper, fill-valve adjustment, and tank water level relative to the overflow",
        [
            "The roof flashing on the vent stack as the first interior check",
            "The water-service corporation stop",
            "The building PRV strainer only",
        ],
    ),
    q(
        "easy",
        "A customer reports a sewer smell at a floor drain. What is a simple early check?",
        "A dry trap is a common cause. Add water (and then find why it dried). Do not pour chemical cleaner as the first diagnostic step.",
        "Whether the trap seal is dry and needs water (and why it dried)",
        [
            "Whether the water heater is in vacation mode",
            "Whether the shower valve is pressure-balancing",
            "Whether the expansion tank precharge is 100 psi",
        ],
    ),
    q(
        "easy",
        "A faucet drips from the spout when closed. What is a likely cause?",
        "A worn cartridge, seat, or washer lets pressure past the seal. This is not a venting problem.",
        "A worn cartridge, seat, or washer",
        [
            "A missing roof vent only",
            "A long trap arm only",
            "A dirty air filter on an HVAC system",
        ],
    ),
    q(
        "easy",
        "Low flow at one faucet with good flow at others often points to:",
        "An aerator screen full of debris after service, or a failing cartridge. Cleaning the aerator is a common first check.",
        "A clogged aerator or debris in that faucet",
        [
            "A city-wide pressure outage",
            "A blocked building sewer",
            "A failed T&P valve as the usual cause",
        ],
    ),
    q(
        "easy",
        "A water heater produces no hot water. The tank is full. For a gas heater, what should be verified early?",
        "Fuel, ignition/pilot or electronic ignition, and that the thermostat is calling. Do not start by replacing the T&P valve.",
        "Fuel supply, ignition, and that the control is calling for heat",
        [
            "The lavatory aerator",
            "The closet flange wax ring",
            "The dishwasher air gap as the first heater check",
        ],
    ),
    q(
        "easy",
        "A clogged lavatory that still overflows into the other bowl of a double sink suggests:",
        "The blockage is downstream of the common waste or the tee, not only in one pop-up. Clear the common path.",
        "The stoppage is in the common waste path, not just one pop-up",
        [
            "The water-supply PRV has failed",
            "The water heater dip tube has failed",
            "The expansion tank is waterlogged as the usual cause",
        ],
    ),
    q(
        "medium",
        "Hot water is rusty but cold water is clear on a tank water heater. What is a likely source?",
        "The tank or dip tube/anode area is a common source of rust in hot water only. If both hot and cold are rusty, look to the service or well instead.",
        "Corrosion or sediment in the water heater",
        [
            "The municipal cold-water main only, because hot and cold always look identical",
            "A dry floor-drain trap",
            "A missing toilet flapper",
        ],
    ),
    q(
        "medium",
        "A customer has lukewarm water only. The heater is firing or drawing current. What should be checked on a tank heater?",
        "A failed dip tube mixes incoming cold into the hot outlet. Elements (electric) or stacking/thermostat issues also matter. Raising temperature to an unsafe level is not the first step.",
        "Dip tube condition, thermostat/element operation, and mixing/crossover",
        [
            "The roof vent cap as the primary cause of lukewarm water",
            "The shower-valve trim finish",
            "The brand of toilet paper",
        ],
    ),
    q(
        "medium",
        "A toilet flushes weakly. The tank fills to the correct waterline and nearby fixtures flow well. What should be evaluated?",
        "With a full tank and good building pressure, look at how water leaves the tank and bowl: flapper or flush-valve opening, rim jets and siphon jet, trapway or drain restriction, and venting. A closed supply stop would usually prevent a full tank. Do not start at the water-heater T&P or a dishwasher loop.",
        "Flush-valve opening, rim/siphon jets, and trapway or drain restriction",
        [
            "The water-heater T&P setting",
            "The building PRV as the only cause, since nearby fixtures already flow well",
            "The dishwasher high loop",
        ],
    ),
    q(
        "medium",
        "A sewage ejector motor runs, but the basin level does not fall and basement fixtures back up. What should be checked?",
        "A running motor does not prove pumping. Confirm the impeller is moving water, the check valve is not stuck closed, the discharge is not blocked, and the basin is vented. A failed-open check valve usually causes rapid cycling after a pump-down rather than a basin that never empties. Do not start at a kitchen aerator.",
        "Whether the pump is actually moving water, then check valve, discharge path, and basin vent",
        [
            "The kitchen faucet aerator only",
            "The ice-maker saddle valve",
            "The shower scald-protection cartridge as the first sewer-pump check",
        ],
    ),
    q(
        "medium",
        "A water-logged expansion tank can cause:",
        "If the tank is full of water (lost air charge), it cannot absorb expansion, so pressure rises and the T&P may drip on each heat cycle.",
        "Rising pressure on each heat cycle and T&P dribbling",
        [
            "A dry trap at a distant floor drain as the usual result",
            "Increased sewer capacity",
            "Lower water-heater recovery by doubling the tank volume with air",
        ],
    ),
    q(
        "medium",
        "A customer reports banging pipes when the washing machine fills. What is a logical service direction?",
        "Quick-closing valves cause water hammer. Check arrestors, loose straps, and high pressure. Do not start by replacing the water heater anode.",
        "Water hammer arrestors, pipe strapping, and supply pressure",
        [
            "The closet-flange wax ring",
            "The AAV listing sticker",
            "The color of the P-trap",
        ],
    ),
    q(
        "medium",
        "Both bowls of a bathroom sink drain slowly, and a toilet on the same wall gurgles. What is the next place to look after the local traps?",
        "A common branch or vent problem can affect several fixtures. Snake the branch and evaluate venting rather than only plunging one bowl repeatedly.",
        "The common branch drain and venting for that bathroom group",
        [
            "The water meter strainer only",
            "The water-heater element only",
            "The outdoor hose-bibb vacuum breaker only",
        ],
    ),
    q(
        "medium",
        "A gas water heater has a yellow, lifting flame and soot. What should the technician do?",
        "Yellow, lifting, sooty flame is incomplete combustion and a carbon-monoxide hazard. Shut the heater down, correct combustion air and venting, then restart only after the flame burns stable and blue and venting is confirmed. Do not leave it firing, starve it of air, or cap the T&P valve.",
        "Shut it down, correct air and venting, and restart only after combustion is verified safe",
        [
            "Close the combustion-air openings to yellow the flame on purpose",
            "Keep it running because yellow flames are more efficient",
            "Cap the T&P valve to raise efficiency",
        ],
    ),
    q(
        "medium",
        "A customer has no cold water in the building but the water heater still has water. What does that suggest?",
        "The cold service is interrupted, but the heater tank still holds water that may feed some hot-side fixtures. Look at the service, meter, PRV, or a closed main valve—not the heater first.",
        "The incoming cold-water service is interrupted upstream of the heater",
        [
            "The heater dip tube has failed as the only explanation",
            "The building sewer is blocked as the only explanation",
            "The toilet flapper is leaking as the only explanation",
        ],
    ),
    q(
        "medium",
        "A pop-up lavatory drain leaks at the pivot rod. What is a typical repair?",
        "The pivot-ball seal/nut is a common leak. Re-gasket or replace the pop-up assembly. This is not a stack vent problem.",
        "Service the pivot-ball seal or replace the pop-up assembly",
        [
            "Replace the main building PRV as the first step",
            "Add a second P-trap in series",
            "Increase water-heater temperature",
        ],
    ),
    q(
        "medium",
        "After replacing a water heater, the hot water smells like rotten eggs. What is a recognized contributing factor?",
        "Sulfate-reducing bacteria can react with a sacrificial anode and produce hydrogen sulfide odor. Treatment may include anode type change and disinfection—not ignoring combustion safety. Confirm it is not a sewer-gas smell from DWV.",
        "Reaction at the sacrificial anode in the presence of sulfate-reducing bacteria",
        [
            "A missing wax ring as the usual cause of hot-water odor",
            "A clogged aerator as the usual cause of sulfur odor in the tank",
            "A high PRV setting as the usual cause of odor",
        ],
    ),
    q(
        "medium",
        "A customer complains of scalding at a lavatory after a water-heater replacement. What should be verified?",
        "Confirm tank temperature, mixing valve operation, and that hot/cold are not reversed at the faucet. Do not leave storage temperature in an unsafe delivered range at the fixture.",
        "Stored water temperature, mixing valve, and hot/cold orientation at the faucet",
        [
            "The sewer cleanout plug tightness only",
            "The dishwasher high loop only",
            "The trap primer line only",
        ],
    ),
    q(
        "hard",
        "A building has simultaneous low hot-water flow and rumbling in the water heater. Cold-water flow is normal. What is a coherent explanation to investigate?",
        "Rumbling often means sediment on the tank bottom. Combined with poor hot flow, dip tube, tank outlet, or a partially closed hot-side valve/mixing valve could also be involved. Flush/inspect the tank and the hot outlet path—do not just raise the thermostat.",
        "Sediment in the tank and restrictions on the hot outlet/mixing path",
        [
            "A blocked building sewer as the first explanation of rumbling",
            "A dry floor drain as the first explanation of rumbling",
            "A missing vent through the roof as the first explanation of rumbling",
        ],
    ),
    q(
        "hard",
        "Several fixtures on one wet wall drain slowly after a remodel. New 2-inch pipe was reduced to 1-1/4 inch to sneak past a stud. What should the technician conclude?",
        "An illegal or undersized reduction will keep clogging. Restore proper size and fittings; repeated snaking is not a repair. Do not enlarge the water-supply PRV to fix a drain.",
        "The undersized section must be corrected; snaking will not repair the layout",
        [
            "Keep snaking weekly as the permanent design",
            "Increase street water pressure to push waste through",
            "Remove fixture traps to compensate for the small pipe",
        ],
    ),
    q(
        "hard",
        "A sewage pump cycles rapidly. The basin fills quickly after each pump-down. What are likely causes?",
        "A failed check valve, a leaking discharge, or a failed-open float can short-cycle. Confirm check-valve direction/condition and float operation before replacing the whole building sewer.",
        "A failed check valve letting water return, or a defective float/control",
        [
            "A clogged lavatory aerator",
            "A water-logged expansion tank",
            "A reversed shower hot/cold cartridge as the usual cause",
        ],
    ),
    q(
        "hard",
        "After a winter freeze, a hose bibb split and a section of interior copper is ballooned. What is the correct repair philosophy?",
        "Freeze damage can appear where the ice expanded, but weakened pipe may exist nearby. Replace damaged sections, open stops that were frozen, and add freeze protection; do not just clamp a split and leave the rest uninspected.",
        "Replace freeze-damaged pipe and fittings and inspect adjacent sections; add freeze protection",
        [
            "Close the split with electrical tape as a permanent repair",
            "Raise water pressure to round the ballooned pipe back into shape",
            "Solder a cap over the T&P valve in case it froze",
        ],
    ),
    q(
        "hard",
        "A customer has repeating drain backups at a kitchen sink after grease-heavy use. A cable snakes through easily, but the line clogs again. What is the most complete service approach?",
        "A cable often pokes a hole through grease while leaving a coating on the pipe wall. Restore the bore by scraping or properly jetting the film off the wall, then change the usage that deposits grease. Do not pour more grease into the line, and do not treat a quick poke-through as a cleaning.",
        "Remove the grease film from the pipe wall (cutter or proper jetting) and address the usage that deposits it",
        [
            "Pour additional grease to lubricate the pipe",
            "Remove the trap permanently so grease cannot collect",
            "Connect the sink to the water-heater drain pan",
        ],
    ),
]

CATEGORIES = [
    {
        "slug": "safety_tools_materials",
        "name": "Safety, Tools & Materials",
        "description": "Jobsite safety, tools, and plumbing materials.",
        "prefix": "PLMB-SAF",
        "questions": SAFETY,
    },
    {
        "slug": "water_supply_systems",
        "name": "Water Supply Systems",
        "description": "Potable water distribution, pressure, and protection.",
        "prefix": "PLMB-WTR",
        "questions": WATER,
    },
    {
        "slug": "drain_waste_vent",
        "name": "Drain, Waste & Vent",
        "description": "DWV principles, traps, vents, and gravity drainage.",
        "prefix": "PLMB-DWV",
        "questions": DWV,
    },
    {
        "slug": "fixtures_installation_fundamentals",
        "name": "Fixtures, Installation & Fundamentals",
        "description": "Fixture setting, water heaters, and installation fundamentals.",
        "prefix": "PLMB-FIX",
        "questions": FIXTURES,
    },
    {
        "slug": "troubleshooting_service",
        "name": "Troubleshooting & Service",
        "description": "Systematic plumbing diagnosis and service.",
        "prefix": "PLMB-DIAG",
        "questions": SERVICE,
    },
]

ASSESSMENT = {
    "slug": "plumbing_knowledge",
    "title": "Plumbing Knowledge Assessment",
    "description": "A knowledge assessment of plumbing safety, water supply, DWV, fixtures, and service. Scores are not a license or certification.",
    "trade_type": "Plumber",
    "company_disclaimer": None,
    "active": True,
    "position": 2,
    "public_result_rule": "best_valid",
}
